# -*- coding: utf-8 -*-
"""Glorieta Gardens Program of Work. Rev 4.0, single document.
Hierarchy: BUCKET > WORK PACKAGE (the hiring unit) > PROJECT > sub-items.
House rules: no em dashes, no marketing language, no glossary section.
Budgets are TBD except where a scope has been approved."""

META = {
    "property": "Glorieta Gardens Apartments",
    "address": "13210 Alexandria Drive, Opa-Locka, FL 33054",
    "owner": "Glorieta Partners, Ltd., c/o R4 GGOL GP LLC",
    "advisor": "APAS Consulting LLC",
    "contract": "Prime Contract No. PC-01",
    "date": "August 9, 2026",
    "version": "Rev. 4.0",
}

INTRO = [
    "This document lists the work discussed at our meeting. It is organized into five buckets. Each bucket is divided into work packages, and each work package is the unit against which specialist expertise will be procured. Under each package are the individual projects.",
    "The granularity is deliberate. It shows the full scope of what the property requires, and it allows work to be authorized package by package rather than all at once.",
    "No amounts are shown except where a scope has already been approved. Several projects cannot be priced until an earlier project establishes what is physically present. Each project is authorized by its own short proposal.",
]

BUCKETS = [
# ============================================================ 01 STORMWATER ==
dict(
 id="01", key="STM", name="Stormwater Management", color="#2F6E7A",
 about=[
   "The stormwater system on this property is not documented. The number of catch basins is unknown, the pipe network is unmapped, and the condition and material of the piping have never been assessed. The retention pond has an unquantified storage capacity, and a second retention area is referenced by several parties but has not been located.",
   "The Stormwater Management Plan is written first, not last. It sets the design basis and the level of service the property will be held to, and it defines the investigation program that follows. Every project in this bucket is a defined part of that plan.",
 ],
 packages=[
  dict(name="Planning and Operating Documents", exp="APAS Consulting, Engineer of Record",
    scope="The governing documents for the stormwater system, issued first and updated as investigation results arrive.",
    projects=[
      dict(n="Stormwater Management Plan, Issue A", flag="FIRST DELIVERABLE",
        s="Design basis, regulatory framework, adopted level of service for each design storm, and a written statement of what is not currently known.",
        sub=["Design basis and regulatory framework",
             "Level of service for the 5, 25 and 100 year storms",
             "Investigation program, sequence and dependencies",
             "Asset identification convention for all field work"]),
      dict(n="Stormwater Management Plan, Issue B",
        s="The final governing document, incorporating survey, geotechnical, modeling and design results with the complete record set.",
        sub=["Consolidated record set: drawings, calculations, permits, test data",
             "System inventory with permanent asset identifiers",
             "As-built configuration and implementation sequence executed"]),
      dict(n="Stormwater Operations Plan",
        s="Inspection and maintenance procedures by asset class, storm response protocols, and the regulatory reporting calendar with named responsibility.",
        sub=["Inspection frequencies, cleaning cycles and sediment removal triggers",
             "Pre-storm readiness and post-storm response procedures",
             "Reporting calendar, evidence retention and annual condition review"]),
    ]),
  dict(name="Records and Subsurface Investigation", exp="Records research, CCTV inspection contractor",
    scope="Establishing what documentation exists, then putting a camera through every pipe to establish what is physically there.",
    projects=[
      dict(n="Stormwater records and permit file review",
        s="Retrieval and assessment of every available record from the City, DERM, RER, SFWMD and the building department, including any record of the second retention area.",
        sub=["Agency records retrieval and reliability rating",
             "Historical aerials and Sanborn map review",
             "Gap register mapped to the field work required to close each gap"]),
      dict(n="Drainage structure inventory and numbering",
        s="Locating and opening every drainage structure on the property and applying the permanent numbering convention.",
        sub=["Structure location, opening and condition note",
             "Permanent identifier applied to every structure and reach"]),
      dict(n="CCTV inspection, catch basin to catch basin",
        s="Continuous distance referenced video of every reach, recording diameter, material, joint type, slope indication, and whether the pipe is perforated or solid.",
        sub=["Line cleaning and jetting to obtain a usable inspection",
             "Full network CCTV with indexed video library",
             "Illicit connection and cross connection flagging"]),
      dict(n="Condition coding and defect register",
        s="NASSCO PACP grading of every observed defect, producing a condition ranked repair and rehabilitation priority list.",
        sub=["Structural and operational defect coding",
             "Sediment depth, collapse and blockage recording",
             "Network geometry file issued to the survey team"]),
    ]),
  dict(name="Survey", exp="Professional Surveyor and Mapper",
    scope="A signed and sealed survey of the site surface and the drainage network, sequenced after the CCTV so the surveyor is locating a known network.",
    projects=[
      dict(n="Site topographic survey",
        s="Full site topography tied to NAVD 88 and the Miami-Dade control network, including finished floor elevations for every building.",
        sub=["Finished floor elevations, building by building",
             "Roadway and parking crowns, gutters, swales and curbs",
             "Signed and sealed drawings plus editable CAD base map"]),
      dict(n="Drainage structure rim and invert survey",
        s="Rim and invert elevation on every pipe entering and leaving every structure identified in the CCTV inventory.",
        sub=["Rim and invert schedule for the full network",
             "Reconciliation against the CCTV inventory, discrepancies resolved"]),
      dict(n="Retention pond survey",
        s="Topographic survey of the banks and control structure, bathymetric survey of the pond bottom, and probing to establish accumulated sediment depth.",
        sub=["Bank, side slope and control structure survey",
             "Bathymetric survey of the sediment surface",
             "Sediment thickness map and current stage storage curve",
             "Comparison against permitted design storage"]),
    ]),
  dict(name="Geotechnical", exp="Geotechnical engineer",
    scope="Measured soil parameters at representative locations, so the hydraulic model runs on site data rather than assumption.",
    projects=[
      dict(n="Soil borings and classification",
        s="Continuous sampling and classification at locations selected from the survey and CCTV results.",
        sub=["Boring locations targeted at proposed exfiltration and retention areas",
             "Continuous sampling with laboratory classification"]),
      dict(n="In situ permeability testing",
        s="Hydraulic conductivity established by the Miami-Dade accepted method at each test location.",
        sub=["Field permeability testing",
             "Design conductivity values issued to the modeling team"]),
      dict(n="Seasonal high water table determination",
        s="The wet season groundwater elevation at each location, which sets the lower design limit for every infiltration feature.",
        sub=["Groundwater elevation measurement and interpretation",
             "Signed and sealed geotechnical report with design parameters"]),
    ]),
  dict(name="Modeling and Analysis", exp="APAS Consulting, Engineer of Record",
    scope="The analytical core of the bucket. Every field project feeds it and every design project is scoped by its results.",
    projects=[
      dict(n="Digital terrain model and dredge volume",
        s="A three dimensional model of the existing sediment surface and the target design bottom, producing a computed dredge quantity before anyone mobilizes.",
        sub=["Existing and design surface models",
             "Computed cut volume with contingency band",
             "Dredge limit drawings and verification protocol"]),
      dict(n="Hydrologic and hydraulic model",
        s="A calibrated model built from the survey base map, the CCTV network geometry, the measured permeability values and the pond stage storage curve.",
        sub=["Model build from measured site data",
             "Calibration against observed flooding history"]),
      dict(n="Design storm analysis and deficiency register",
        s="The 5, 25 and 100 year storms run against two separate criteria: finished floor protection for every building, and roadway passability for emergency access.",
        sub=["Flood maps and inundation depths by return period",
             "Finished floor and roadway risk assessment, building by building",
             "Deficiency register with the hydraulic cause identified",
             "Improvement scenarios with the risk reduction each one delivers"]),
    ]),
  dict(name="Sediment Management", exp="Environmental consultant, certified laboratory, dredging contractor",
    scope="Characterising the pond sediment before it is disturbed, then removing it and restoring the storage volume.",
    projects=[
      dict(n="Sediment sampling and characterization",
        s="Representative sampling across the pond footprint and at depth, analyzed for the contaminants indicated by the adjacent industrial land uses.",
        sub=["Sampling and analysis plan",
             "Laboratory analysis for metals and petroleum constituents",
             "Waste profile prepared for the receiving facility"]),
      dict(n="Disposal pathway approval",
        s="Written acceptance from the receiving facility obtained before dredging begins, with hauling and manifesting requirements confirmed.",
        sub=["Facility acceptance in writing",
             "Hauling, manifesting and chain of custody protocol"]),
      dict(n="Retention pond dredging",
        s="Removal of accumulated sediment to the design bottom elevation within the defined dredge limits, with turbidity and erosion controls in place.",
        sub=["Turbidity and erosion control, dewatering and staging",
             "Dredging to target elevation",
             "Bank restoration, stabilization and littoral planting"]),
      dict(n="Disposal and post dredge verification",
        s="Transport and disposal under full manifest, followed by a verification survey confirming the storage volume recovered.",
        sub=["Manifested transport and disposal",
             "Post dredge verification survey and storage recovery certification"]),
    ]),
  dict(name="Design, Permitting and Construction", exp="Engineer of Record, general contractor",
    scope="Designed and built to the capacity the model requires. Scope is set by the modeling results, so these projects are proposed after that work completes.",
    projects=[
      dict(n="Retention pond design and reconfiguration",
        s="The pond designed to the target storage volume, with side slopes, safety shelf, maintenance access and a control structure sized to the permitted discharge rate.",
        sub=["Stage storage discharge calculations",
             "Side slopes, safety shelf and littoral zone",
             "Weir and orifice control structure design"]),
      dict(n="Stormwater lift station assessment and design",
        s="Condition, capacity and siting of the existing pumping arrangement evaluated against modeled demand, and design of whatever the answer requires.",
        sub=["Condition and firm capacity assessment",
             "Siting evaluation relative to the pond and modeled inflow points",
             "Wet well, pumps, controls, standby power and telemetry design"]),
      dict(n="Site regrading and drainage design",
        s="Reshaping the ground so water drains by gravity to the intended collection points, with conveyance improvements where the model identifies capacity deficiency.",
        sub=["Grading design to the adopted level of service",
             "Swales, inlets and pipe upsizing where required",
             "Phasing to maintain resident access and emergency circulation"]),
      dict(n="Second retention area and exfiltration trench",
        s="Conditional on the model. Locates and assesses the second retention area, or closes the question on the record, and designs an exfiltration trench sized to any residual storage deficit.",
        sub=["Second retention area investigation, located and assessed or formally closed",
             "Exfiltration trench design using the measured hydraulic conductivity",
             "Options comparison on capacity, cost and maintenance burden"], cond=True),
      dict(n="Permitting and construction",
        s="Permits through Miami-Dade DERM, SFWMD and the City of Opa-Locka, then construction with survey verification of finished grades.",
        sub=["Permit submittals and agency review management",
             "Construction of regrading and any supplemental features",
             "As-built survey verification and record drawings"]),
    ]),
 ]),

# ================================================================ 02 SEWER ===
dict(
 id="02", key="SWR", name="Sewer Extension", color="#3B5E80",
 about=[
   "The sanitary sewer extension is built. Two items remain and they are different in kind. The first is administrative: transferring the asset to the City of Opa-Locka through a formal conveyance package. Until the City accepts it in writing, the system remains the owner's asset, maintenance obligation and warranty exposure.",
   "The second is operational. There is no measurement of what leaves the property. Glorieta is the largest single discharger into the City pump station, and without a meter there is no defensible answer to any question about volume, infiltration and inflow, or billing.",
 ],
 packages=[
  dict(name="Conveyance and Close-Out", exp="APAS Consulting, Engineer of Record, surveyor, contractors, owner's counsel",
    scope="Running the City of Opa-Locka Utilities Conveyance Checklist to completion, item by item, with a named owner against every line.",
    projects=[
      dict(n="Conveyance checklist administration", status="In progress",
        s="Every checklist item tracked to completion with evidence attached, and the acceptance package transmitted and tracked through City review.",
        sub=["Item by item tracking with named owner and date",
             "Acceptance package assembly and transmittal",
             "City review management to written acceptance"]),
      dict(n="Engineer of Record certifications", status="In progress",
        s="The sealed engineering deliverables the City requires: record drawings, infiltration and exfiltration certification, FDEP sewer certification, General Permit and In-Service Letter.",
        sub=["Signed and sealed record drawings and record drawing disk",
             "Infiltration and exfiltration certification",
             "FDEP certification, General Permit and In-Service Letter",
             "Latitude and longitude detail sheet"]),
      dict(n="As-built survey and constructed sewer CCTV", status="In progress",
        s="The surveyor's signed and sealed as-built reconciled against the record drawings, and the contractor's CCTV of the constructed gravity sewer.",
        sub=["Sealed as-built survey in PDF and editable CAD",
             "CCTV video, Sewer Report and Master Utility Sheet",
             "Field completion and restoration for the City preliminary inspection"]),
      dict(n="Contractor close-out and warranties", status="In progress",
        s="Punch list completion, final lien waivers, material certifications, test results, permit close-outs, and the three twelve month warranties by building group.",
        sub=["Punch list, lien waivers, material certifications and test results",
             "Asphalt and sod final quantities",
             "Warranties executed: Bldg 3 South with Bldg 4, Bldg 5 with Bldg 6, Bldg 3 North",
             "Retainage release per the contract schedule"]),
      dict(n="Legal and security items", status="In progress",
        s="Support to owner's counsel on the title and security instruments the City requires at transfer.",
        sub=["Attorney's and Owner's Affidavits",
             "Warranty Deed, Bill of Sale and UCC subordination",
             "Utilities Performance Security and final obligations bond"]),
    ]),
  dict(name="Flow Measurement", exp="Engineer of Record, contractor, City of Opa-Locka",
    scope="A permanent meter at the point of discharge, so total flow leaving the property is measured rather than inferred.",
    projects=[
      dict(n="Metering structure design and permitting",
        s="A permanent vault or dedicated manhole sized and located for accurate hydraulic conditions and safe permanent access, permitted through the City and DERM.",
        sub=["Confirmation of the single discharge point and absence of any bypass",
             "Structure and meter technology selection with redundancy",
             "Telemetry and continuous data logging design"]),
      dict(n="Construction, commissioning and calibration",
        s="Construction, commissioning and field calibration, establishing the certified accuracy baseline.",
        sub=["Structure construction and meter installation",
             "Field calibration and accuracy certificate",
             "Data feed integrated into ProjOS"]),
      dict(n="Baseline infiltration and inflow study",
        s="Diurnal flow curves and wet weather response measured at the new meter, quantifying how much of the discharge is groundwater and rainwater rather than sanitary flow.",
        sub=["Diurnal flow curve and pre-dawn minimum analysis",
             "Wet weather response measurement",
             "Quantified infiltration and inflow with reduction priorities"]),
    ]),
 ]),

# ================================================================ 03 WATER ===
dict(
 id="03", key="WTR", name="Water Systems", color="#4E7D5E",
 about=[
   "The location of the water distribution system on this property is not established. Until it is, every modification is planned against assumption, whether that is a meter box, a backflow device or a trench for stormwater work.",
   "The records and file assessment is approved and starts the sequence. Depending on what the records prove, the system is either verified against documentation or located in the field. Three construction programs follow: meter boxes, backflow prevention, and an irrigation well for the common areas.",
 ],
 packages=[
  dict(name="Records and Field Location", exp="APAS Consulting, surveyor, subsurface utility locating contractor",
    scope="Establishing where the water system is, from records where they hold up and from the field where they do not.",
    projects=[
      dict(n="Water and sewer records and file assessment", status="Scope approved",
        flag="SCOPE APPROVED", budget="$3,000 lump sum",
        s="Review of all utility records from the City, Miami-Dade WASD, DERM, RER and the building department, with each document rated for reliability. Scope widened from wastewater only to all utilities.",
        sub=["Agency and developer records retrieval",
             "Permit history: mains, services, meters, backflow devices",
             "Reliability rating on every document, sealed as-built through to sketch",
             "Gap register and recommendation on the field verification path"]),
      dict(n="Subsurface utility locating",
        s="Electromagnetic pipe locating and ground penetrating radar across the site, with all surface appurtenances located and elevated.",
        sub=["Electromagnetic and GPR designation across the site",
             "Valve, hydrant, meter and service point survey",
             "Register of unknown or abandoned lines"]),
      dict(n="Potholing verification",
        s="Small test excavations at critical locations and at points of future work, confirming horizontal position, depth, diameter and material.",
        sub=["Vacuum excavation at critical and future work points",
             "Depth, diameter and material confirmed and recorded"]),
      dict(n="Water system as-built",
        s="A signed and sealed as-built reconciling all field data against the records, in PDF and editable CAD.",
        sub=["Field data reconciled against records, conflicts resolved",
             "Sealed as-built with appurtenance schedule"]),
    ]),
  dict(name="Metering", exp="Engineer of Record, contractor, City of Opa-Locka",
    scope="APAS designs, permits and builds the boxes and settings. The City brings and installs its own meters.",
    projects=[
      dict(n="Meter count, sizing and layout",
        s="Meter requirements determined from the as-built and the service configuration.",
        sub=["Meter schedule with sizing and locations",
             "Locations set for permanent access and vehicle protection"]),
      dict(n="Meter box design and permitting",
        s="Installations designed to City of Opa-Locka and Miami-Dade WASD standards and permitted.",
        sub=["Box, setting, service piping and appurtenance design",
             "Permits through the City and WASD"]),
      dict(n="Construction and City meter coordination",
        s="Construction with resident water service maintained, then coordination of the City meter installation, witnessed and documented.",
        sub=["Phased construction with noticed interruptions",
             "City installation scheduled, inspected and witnessed",
             "Meter number to service address register"]),
    ]),
  dict(name="Cross Connection Control", exp="Engineer of Record, contractor, certified backflow tester",
    scope="Installation of the required devices and the standing annual testing obligation that follows them.",
    projects=[
      dict(n="Hazard survey and device schedule",
        s="Every connection surveyed and the required device type determined by hazard classification.",
        sub=["Cross connection hazard survey",
             "Device type and size schedule by location"]),
      dict(n="Design, permitting and installation",
        s="Installations designed to City and WASD standards with permanent access and traffic protection, then procured, installed and commissioned.",
        sub=["Design and permitting",
             "Procurement, installation and commissioning"]),
      dict(n="Certification and annual testing program",
        s="Initial certification by a certified tester filed with the City, and every device enrolled in the annual testing program.",
        sub=["Initial certification testing and City filing",
             "Device register with serial numbers and test history",
             "Annual testing schedule with scheduled reminders in ProjOS"]),
    ]),
  dict(name="Irrigation Supply", exp="Hydrogeologist, licensed well contractor",
    scope="A dedicated non potable source for common area irrigation, removing that demand from the potable system.",
    projects=[
      dict(n="Hydrogeologic siting and permitting",
        s="Aquifer selection, expected yield and required setbacks, permitted through DERM and SFWMD including water use authorization.",
        sub=["Siting report with yield and water quality expectation",
             "Setbacks from sanitary and environmental features",
             "Placement coordinated with the environmental monitoring well program",
             "DERM well permit and SFWMD water use permit"]),
      dict(n="Well drilling, development and testing",
        s="Drilling, development and testing to confirm yield and water quality.",
        sub=["Drilling and well development",
             "Yield and water quality testing"]),
      dict(n="Pump, controls and distribution",
        s="Pump, controls and above ground equipment with backflow protection, and the irrigation distribution to the common areas.",
        sub=["Pump, controls and backflow protection",
             "Zoned distribution and controller",
             "Commissioning and operations manual"]),
    ]),
  dict(name="Non Revenue Water", exp="APAS Consulting",
    scope="Not yet scoped. Raised for discussion before anything is proposed.",
    projects=[
      dict(n="Water balance and non revenue water assessment", status="For discussion",
        flag="FOR DISCUSSION",
        s="An AWWA M36 water balance establishing how much of the water the property buys is never billed, and how much of that gap is recoverable. Timing is relevant: the meter box program and the irrigation well both change the measurement basis, so a baseline now and a repeat after is worth more than either alone.",
        sub=["System input volume from City metering, with meter accuracy verified",
             "Apparent losses: meter under-registration, data handling, unrecorded connections",
             "Real losses and Infrastructure Leakage Index",
             "Minimum night flow analysis and district metered area evaluation",
             "Annual value at current City rates with ranked recovery measures"]),
    ]),
 ]),

# ======================================================== 04 ENVIRONMENTAL ===
dict(
 id="04", key="ENV", name="Environmental Services and Regulatory Compliance", color="#6E5A86",
 about=[
   "The property is surrounded by industrial neighbors, including junkyards. The purpose of this work is to establish, on the record and for the owner's own protection, whether contamination is migrating onto the property from adjacent parcels. If it is, the owner needs to know first and document it first.",
   "Running alongside is the standing compliance obligation. The Consent Order closes only when every enumerated corrective action is complete, documented and released in writing. Permits, reporting and annual certifications continue regardless.",
 ],
 packages=[
  dict(name="Off-Site Source Investigation", exp="APAS Consulting, environmental consultant",
    scope="Records based investigation that scopes the entire environmental program. Well locations, the analytical parameter list and sampling frequency all follow from it.",
    projects=[
      dict(n="Adjacent property file and database review",
        s="Current and historical use of every adjacent parcel, with the junkyard and salvage operations as the focus, searched across DERM, FDEP and EPA records.",
        sub=["RCRA, CERCLIS, petroleum storage and industrial waste file searches",
             "Enforcement history and contamination assessment reports by parcel",
             "Historical aerials, Sanborn maps and city directories"]),
      dict(n="Groundwater gradient and plume vector analysis",
        s="Flow direction and gradient across the property, and which boundaries sit downgradient of which sources.",
        sub=["Gradient determination from regional and site data",
             "Probable migration pathways and first arrival points"]),
      dict(n="Contaminants of concern and parameter list",
        s="The specific analytes worth testing for, based on documented use and documented releases rather than a generic panel.",
        sub=["Contaminants of concern with the documented basis for each",
             "Monitoring well siting recommendation and analytical parameter list"]),
    ]),
  dict(name="Monitoring Well Network", exp="Environmental consultant, licensed well contractor",
    scope="A permanent boundary well network positioned by the plume analysis. Working assumption is a minimum of two wells per side.",
    projects=[
      dict(n="Well siting plan and DERM permitting",
        s="Final well count, locations and screen intervals, with upgradient wells for background and downgradient wells for detection.",
        sub=["Siting plan from the plume vector analysis",
             "Well construction design to DERM standards",
             "DERM well permits"]),
      dict(n="Well installation, development and survey",
        s="Drilling, installation, development and survey of each well, with measuring point elevations tied to NAVD 88.",
        sub=["Drilling, installation and development with completion logs",
             "Measuring point elevations to NAVD 88",
             "Initial groundwater elevation round confirming actual flow direction"]),
    ]),
  dict(name="Groundwater Monitoring", exp="Environmental consultant, Florida certified laboratory",
    scope="Baseline and recurring sampling. A single round gives a concentration. A sequence gives direction and trend, which is what answers the question.",
    projects=[
      dict(n="Sampling and analysis plan",
        s="Methods, parameters, purging protocol and quality control, prepared to DERM acceptable standards.",
        sub=["Parameter list and method selection",
             "Purging, field parameter and chain of custody protocol"]),
      dict(n="Baseline and recurring sampling rounds",
        s="Full network sampling with synoptic water level measurement each round, analyzed at a Florida certified laboratory.",
        sub=["Baseline round across the full network",
             "Recurring rounds at the established frequency",
             "Laboratory data packages with full quality control"]),
      dict(n="Plume behavior and trend analysis",
        s="Results evaluated against DERM and FDEP groundwater cleanup target levels, and analyzed across rounds for source attribution and trend direction.",
        sub=["Comparison against cleanup target levels",
             "Concentration gradient and trend across rounds",
             "Determination of migration onto the property and any impact"]),
      dict(n="Findings report and regulatory strategy",
        s="A defensible finding, a recommended course of action, and a deliberate approach to the City and DERM on the owner's timing rather than in response to an inquiry.",
        sub=["Stated conclusion with the evidentiary basis",
             "Source attribution supporting the owner's position on responsibility",
             "Recommended action and engagement strategy for the City and DERM"]),
    ]),
  dict(name="Regulatory Compliance", exp="APAS Consulting, owner's counsel",
    scope="Closing the Consent Order and keeping every standing obligation current. This runs continuously.",
    projects=[
      dict(n="Consent Order compliance matrix and evidence file", status="Active",
        s="Every enumerated corrective action tracked with its requirement, status, evidence and responsible party, mapped to the program projects that satisfy it.",
        sub=["Compliance matrix mapped to program projects",
             "Evidence file per action: drawings, certifications, tests, permits",
             "Periodic progress reports brought current and maintained"]),
      dict(n="Consent Order close-out", status="Active",
        s="Remaining gaps resolved, the close-out request submitted with the complete evidence package, and written termination pursued and retained.",
        sub=["Gap resolution plan",
             "Close-out submittal package",
             "Written termination retained in the permanent record"]),
      dict(n="Permit register and periodic reporting", status="Active",
        s="The master permit and obligation register across the City, DERM, RER, SFWMD and FDEP, with a reporting calendar carrying named responsibility and lead time alerts.",
        sub=["Permit register, renewals and condition compliance",
             "Reporting calendar with lead time alerts",
             "Annual certifications including backflow device testing",
             "Regulator inspections, inquiries and correspondence",
             "Flood event readiness, response and post-event reporting"]),
    ]),
 ]),

# ===================================================== 05 PROGRAM DELIVERY ===
dict(
 id="05", key="PMO", name="Program Management and ProjOS", color="#A8842C",
 about=[
   "The work above spans four systems, three regulators and multiple specialist contractors. This bucket is the function that holds scope, sequence and delivery under control across all of it, and keeps the owner from having to adjudicate between contractors.",
   "Everything is instantiated in ProjOS so that each project carries its scope, deliverables, permits, documents and current status in one record the owner can open at any time.",
 ],
 packages=[
  dict(name="Program Delivery", exp="APAS Consulting",
    scope="Day to day management on site and program level control across all buckets. Continuous under annual authorization.",
    projects=[
      dict(n="Site and contractor management", status="Active",
        s="Day to day coordination, sequencing, quality and safety oversight of on-site crews and contractors.",
        sub=["Daily coordination and sequencing",
             "Quality and safety oversight",
             "Interface management where packages touch"]),
      dict(n="Procurement, change and cost control", status="Active",
        s="Procurement and administration of all specialty subcontracts, change management, and pay application review verified against installed work.",
        sub=["Specialty subcontract procurement and administration",
             "Change order review, negotiation and substantiation",
             "Pay application review and lien waiver control",
             "Warranty tracking and retainage management"]),
      dict(n="Schedule, permits and owner reporting", status="Active",
        s="The integrated master schedule with the cross bucket dependency map maintained live, agency coordination, and monthly owner reporting.",
        sub=["Integrated master schedule and dependency map",
             "Agency coordination across the City, DERM, RER, SFWMD and FDEP",
             "Monthly owner report on status, risk and schedule performance",
             "Risk register with mitigation owners and dates"]),
    ]),
  dict(name="Operating Record", exp="APAS Consulting",
    scope="ProjOS as the single operating record for the property. Recommended as a live demonstration rather than a written description.",
    projects=[
      dict(n="Program register and dashboards", status="To be demonstrated",
        s="Every project in this document instantiated as a live object with scope, deliverables, dependencies and approval status, rolled up by bucket.",
        sub=["Project register with bucket roll-up",
             "Proposal and approval tracking from issue to completion",
             "Owner facing dashboards for status, schedule and risk"]),
      dict(n="Document control and compliance engine", status="To be demonstrated",
        s="Every drawing, permit, certification and report attached to the project that produced it, with the permit register and reporting calendar driving automated alerts.",
        sub=["Document control with evidence attached at project level",
             "Compliance engine with reporting calendar and lead time alerts",
             "Live data feeds from the sewer flow meter and groundwater monitoring",
             "Operations layer running the sewer, water and stormwater plans as scheduled tasks"]),
    ]),
 ]),
]

SEQUENCE = [
 ("A", "Authorize now, no predecessors",
  "The Stormwater Management Plan Issue A, the approved water and sewer records assessment, the stormwater records review, and the environmental file review. Three of these are records work that governs the cost of everything after them.",
  "STM 1.1.1, STM 1.2.1, WTR 3.1.1, ENV 4.1.1"),
 ("B", "Field investigation",
  "CCTV, survey, geotechnical, pond survey, water system locating, and monitoring well installation. This phase converts assumption into measured fact.",
  "STM 1.2, STM 1.3, STM 1.4, WTR 3.1, ENV 4.2"),
 ("C", "Analysis",
  "The hydraulic model, the dredge volume, the sediment characterization and the groundwater sampling. Nothing downstream can be priced until this phase closes.",
  "STM 1.5, STM 1.6.1, ENV 4.3"),
 ("D", "Design and permitting",
  "Pond, lift station, regrading and supplemental features designed to the modeled capacity. Meter boxes, backflow and the irrigation well designed off the verified as-built. Sewer flow meter designed and permitted.",
  "STM 1.7, WTR 3.2, WTR 3.3, WTR 3.4, SWR 2.2"),
 ("E", "Construction",
  "Dredging, regrading and any supplemental features. The largest physical scope in the program and the last to be defined.",
  "STM 1.6.3, STM 1.7.5"),
 ("F", "Operationalize",
  "Management Plan Issue B, the Operations Plan, and written termination of the Consent Order. Compliance, program management and ProjOS continue.",
  "STM 1.1.2, STM 1.1.3, ENV 4.4"),
]

COMMERCIAL = [
 ("Authorization", "One short proposal per project. An executed proposal is the authorization and the basis of the work. Projects can be authorized individually, in any order the dependencies allow."),
 ("APAS self-performed", "Lump sum fixed fee, stated in the proposal. Covers planning, records review, modeling, analysis, design coordination, compliance and program management."),
 ("Specialty subcontract", "Procured, contracted, supervised and paid through APAS at contracted cost plus 10 percent overhead and 10 percent profit. Underlying cost available on request."),
 ("Recurring services", "Program management, regulatory compliance and the ProjOS operating record are monthly under an annual authorization."),
 ("Exclusions", "Permit and agency review fees, records request fees, the Utilities Performance Security, the final obligations bond and City supplied water meters."),
]
