# -*- coding: utf-8 -*-
"""Glorieta Gardens — Program of Work. Single source of truth.
Rev 2.0 — no durations, no dollar amounts (except the one approved scope).
Every project is authorized by its own short proposal."""

PROGRAM = {
    "property": "Glorieta Gardens Apartments",
    "address": "13210 Alexandria Drive, Opa-Locka, FL 33054",
    "owner": "Glorieta Partners, Ltd. — c/o R4 GGOL GP LLC",
    "advisor": "APAS Consulting LLC",
    "date": "August 9, 2026",
    "version": "Rev. 2.0",
    "contract_ref": "Prime Contract No. PC-01",
}

TBD = "TBD"

# APAS delivery roles
SELF = "APAS self-performed"
MANAGED = "APAS-managed · specialty subcontract"
HYBRID = "Hybrid — APAS professional services + subcontract"

# Fee basis
LS = "Lump sum — fixed fee proposal"
LS_PLUS = "Lump sum professional services + subcontracted work at cost plus 10% overhead and 10% profit"
COST_PLUS = "Subcontracted at cost plus 10% overhead and 10% profit; APAS administers"
MONTHLY = "Monthly professional services"

PROPOSED = "Proposal to be issued"
APPROVED = "Scope approved — proposal to follow"
DISCUSS = "For discussion before anything is scoped"

BUCKETS = [
    {
        "id": "STM", "num": "01", "name": "Stormwater Management",
        "file": "01-Stormwater-Management.html",
        "color": "#2F6E7A", "tint": "rgba(47,110,122,0.09)",
        "tagline": "The plan comes first. Everything else is written into it.",
        "posture": "Stormwater Management Plan is the program's first deliverable.",
        "summary": "We do not currently know, with engineering certainty, what the stormwater system on this property is. Not how many catch basins. Not where the pipes run, what size they are, what they are made of, or whether they are intact. There is a retention pond of unquantified capacity and a second retention area that people reference but nobody has located. Every one of those unknowns is a flood-risk unknown. So the Stormwater Management Plan is written first — not last. It establishes the design basis, the level of service the property will be held to, and the investigation program required to get there. Every project that follows is then a defined chapter of that plan rather than a standalone expense, and the plan is reissued as a final governing document once the data is in.",
        "why": "Flooding is the fastest way this property generates a life-safety event, a resident claim, an insurance loss, and a regulatory finding — all at once. Writing the plan first means every dollar spent afterwards has a stated purpose inside a document the owner, the engineer and the regulator all read the same way.",
    },
    {
        "id": "SWR", "num": "02", "name": "Sewer Extension",
        "file": "02-Sewer-Extension.html",
        "color": "#3B5E80", "tint": "rgba(59,94,128,0.09)",
        "tagline": "Built. Now we hand it over — and we measure what leaves.",
        "posture": "Construction complete. Closing out and instrumenting.",
        "summary": "The sanitary sewer extension is physically built. Two things remain, and they are different in kind. The first is administrative: transferring the asset to the City of Opa-Locka through a formal conveyance package. The second is operational: putting a permanent flow meter at the point where wastewater leaves the property, so that Glorieta — the system's largest single discharger — can prove exactly what it sends to the City's pump station.",
        "why": "Until conveyance closes, the sewer remains the owner's asset, the owner's maintenance obligation, and the owner's warranty exposure. Until the meter is in, every flow question is an argument instead of a fact.",
    },
    {
        "id": "WTR", "num": "03", "name": "Water Systems",
        "file": "03-Water-Systems.html",
        "color": "#4E7D5E", "tint": "rgba(78,125,94,0.10)",
        "tagline": "Find the pipes. Then meter, protect, and supplement them.",
        "posture": "Records and file assessment approved. Balance to be proposed.",
        "summary": "We need to know where our water pipes are before we touch anything else. That begins with the records and file assessment — originally discussed for wastewater, now necessarily widened to every utility record we can obtain. If the records are good, we field-verify them and produce an as-built. If they are not, we run a full field verification survey. From that foundation, three construction projects follow: meter boxes (we design, permit and build; the City sets its meters), backflow prevention, and an irrigation well to serve the common areas. One further item sits at the end of this bucket, flagged for discussion rather than proposed: a non-revenue water assessment, which asks a question none of the other projects ask — how much of the water this property buys is never billed to anybody.",
        "why": "Any future modification — a meter box, a backflow device, a trench for stormwater — is a guess until the water system is located. Guessing is how you hit a live main. And once the system is located and metered, it becomes possible for the first time to find out what the property is paying for and not receiving.",
    },
    {
        "id": "ENV", "num": "04", "name": "Environmental Services & Regulatory Compliance",
        "file": "04-Environmental-Regulatory.html",
        "color": "#6E5A86", "tint": "rgba(110,90,134,0.09)",
        "tagline": "Prove what came from off-site. Close the Consent Order.",
        "posture": "Ongoing obligation. Investigation scope to be defined.",
        "summary": "Glorieta Gardens is surrounded by industrial neighbours, including junkyards. The purpose of this bucket is to establish, on the record and for the owner's own protection, whether contamination is migrating onto the property from adjacent parcels. That means an extensive file review of the surrounding properties, a plume analysis, and a monitoring well network on the boundaries — a minimum of two wells per side. Running alongside it is the standing compliance obligation: closing out the Consent Order completely and keeping water, sewer and stormwater operating in conformance with their permits at both local and state level.",
        "why": "If a neighbour's plume has reached this property, the owner needs to know it first, document it first, and control the narrative with DERM and the City — not learn about it during a transaction.",
    },
    {
        "id": "PMO", "num": "05", "name": "Program Management & ProjOS",
        "file": "05-Program-Management-ProjOS.html",
        "color": "#A8842C", "tint": "rgba(168,132,44,0.10)",
        "tagline": "One operating record. Every project, every document, every obligation.",
        "posture": "Active and continuing.",
        "summary": "The four program buckets above are only manageable if something holds them together. APAS provides day-to-day project management for the crews on site and program-level management across all four buckets — scope control, change management, schedule, pay application review, permit tracking and regulatory correspondence. All of it is instantiated in ProjOS, so that every project carries its scope, deliverables, permits, documents and current status in one operating record the owner can open at any time.",
        "why": "Thirty-one projects across four systems and three regulators is not a spreadsheet problem. Without a single operating record, the owner is reconstructing the truth from email every time a question is asked.",
    },
]

P = [
# ============================== STORMWATER ====================================
dict(
    id="STM-01", bucket="STM", name="Stormwater Management Plan",
    type="Planning · Engineering", status="First deliverable", flag="FIRST DELIVERABLE",
    headline="Write the plan first. It defines the design basis, the level of service, and every project that follows.",
    context="This is the program's first deliverable, and putting it first is a deliberate choice. A management plan written at the end is a filing exercise. Written at the beginning, it is the instrument that governs everything: it states what the stormwater system is meant to achieve, what standard the property will be held to, what has to be investigated to get there, and in what order. Every project after it becomes a defined chapter of a plan the owner, the engineer and the regulator all read the same way — rather than a series of separate expenses nobody can connect to each other. The plan is issued in two parts: the framework and roadmap now, and the final governing document once the investigation and modelling results are in.",
    scope=[
        "Issue A — Framework and roadmap. Establish the design basis, the regulatory framework, and the adopted level of service the property will be held to for each design storm.",
        "Define the stormwater system as currently understood, and state explicitly and in writing what is not known.",
        "Define the investigation program required to close each gap, and set the sequence and dependencies between the projects that follow.",
        "Establish the asset identification convention so every structure and pipe carries a permanent identifier from the first day of field work.",
        "Define the performance criteria against which the finished system will be judged.",
        "Issue B — Final governing plan. Incorporate the investigation, survey, geotechnical, modelling and design results as they arrive.",
        "Consolidate the complete record set: drawings, calculations, permits, test data and certifications, into one governing document.",
        "Document the implementation sequence actually executed and the as-built configuration of the system.",
        "Publish and maintain the plan in ProjOS as the live reference for the stormwater system.",
    ],
    deliverables=[
        "Stormwater Management Plan — Issue A: framework, design basis, level of service, investigation roadmap",
        "Project sequence and dependency map",
        "Asset identification convention",
        "Performance criteria",
        "Stormwater Management Plan — Issue B: final governing document with the complete record set",
        "Live plan published in ProjOS",
    ],
    pred=[], party="APAS · Engineer of Record",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services. Issue A and Issue B proposed separately so the owner authorises the framework without committing to the final document before the scope of investigation is known.",
    driver="NPDES MS4 · Miami-Dade Chapter 24 · SFWMD Environmental Resource Permit · Consent Order close-out",
),
dict(
    id="STM-02", bucket="STM", name="Stormwater Records & File Review",
    type="Investigation", status="Not started",
    headline="Determine what documentation of the stormwater system actually exists before spending a dollar in the field.",
    context="This is the least expensive project in the stormwater bucket and it governs the cost of every project after it. If usable as-builts and drainage permits exist, large parts of the field program shrink. If they do not, we know immediately that field verification is the starting point rather than the fallback — and we scope and price accordingly.",
    scope=[
        "Search and retrieve records from the City of Opa-Locka, Miami-Dade DERM, Miami-Dade RER, the Water Control District, SFWMD and the building department.",
        "Pursue original developer, architect and engineer files, plats, easements, drainage permits and prior modification permits.",
        "Review historical aerials and Sanborn maps to identify the original drainage configuration and any later alterations.",
        "Specifically pursue any record of the second retention area — its location, permitted volume and whether it was ever built.",
        "Produce a records inventory and, more importantly, a gap register: what we have, what we do not have, and what each gap costs to close in the field.",
    ],
    deliverables=[
        "Records inventory with source and reliability rating on every document",
        "Gap register mapped to the field projects required to close each gap",
        "Recommendation memo: documentation-led path or field-led path",
        "Findings written into the Stormwater Management Plan",
    ],
    pred=["STM-01"], party="APAS",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services. Agency records request and reproduction fees passed through at cost.",
    driver="NPDES MS4 · Miami-Dade Chapter 24 · SFWMD Environmental Resource Permit history",
),
dict(
    id="STM-03", bucket="STM", name="CCTV Inspection of the Underground Stormwater System",
    type="Investigation", status="Not started",
    headline="Send a camera through every pipe, catch basin to catch basin, and find out what is actually down there.",
    context="Nothing downstream can be designed responsibly without this. It answers, with video evidence, the questions we currently cannot answer: how many catch basins do we have, where do the pipes run, what size are they, what are they made of, are they perforated or solid, and are any of them collapsed. It is a non-intrusive condition assessment — no digging, no excavation, no disruption to residents.",
    scope=[
        "Locate, open and inventory every drainage structure on the property; apply the permanent numbering convention set in the Stormwater Management Plan.",
        "Clean and jet lines as required to obtain a usable inspection.",
        "CCTV every reach, catch basin to catch basin, with continuous video and distance-referenced logging.",
        "Record for every reach: pipe diameter, material, joint type, slope indication, and whether the pipe is perforated or solid.",
        "Grade structural and operational condition to NASSCO PACP standard — cracking, deformation, offset joints, root intrusion, sediment depth, and full or partial collapse.",
        "Flag illicit connections and any discharge that does not belong in a stormwater line.",
        "Deliver a condition-ranked defect register that drives the repair and rehabilitation priority list.",
        "Hand the pipe network geometry directly to the survey team so the survey is verifying a known network rather than discovering one.",
    ],
    deliverables=[
        "Complete structure and pipe inventory with permanent IDs",
        "Full CCTV video library, indexed and reach-referenced",
        "NASSCO PACP condition report with defect coding",
        "Condition-ranked defect and rehabilitation priority register",
        "Network geometry file issued to survey",
    ],
    pred=["STM-02"], party="APAS · CCTV specialty contractor",
    role="MANAGED", fee="COST_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Specialty subcontract procured and administered by APAS. Heavily obstructed or collapsed reaches requiring point excavation to access are handled as a separate authorised item.",
    driver="NPDES MS4 illicit discharge detection · Miami-Dade Chapter 24 · Consent Order corrective actions",
),
dict(
    id="STM-04", bucket="STM", name="Topographic & Underground Utility Survey",
    type="Survey", status="Not started",
    headline="Produce a signed and sealed survey of the site surface and the drainage network, informed by what the camera found.",
    context="The survey is sequenced deliberately after the CCTV rather than before it. Running it second means the surveyor is locating and elevating a network we already understand, rather than guessing at inverts and missing structures nobody knew existed. That sequencing is what makes the survey a foundation document instead of a partial one.",
    scope=[
        "Topographic survey of the full site: finished floor elevations of every building, roadway and parking crowns and gutters, swales, curbs and site boundaries.",
        "Locate and elevate every drainage structure identified in the CCTV inventory — rim and invert on every pipe entering and leaving.",
        "Tie the survey to NAVD 88 and to the Miami-Dade County control network.",
        "Reconcile the surveyed network against the CCTV inventory and resolve every discrepancy before sealing.",
        "Deliver signed and sealed drawings plus editable CAD, and a survey-grade base map that becomes the single geometric basis for all subsequent stormwater design.",
    ],
    deliverables=[
        "Signed and sealed topographic and utility survey",
        "Editable CAD (DWG/DXF) base map",
        "Rim and invert schedule for every structure",
        "Reconciliation memo against the CCTV inventory",
    ],
    pred=["STM-03"], party="APAS · Professional Surveyor & Mapper",
    role="MANAGED", fee="COST_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Licensed survey subcontract procured and administered by APAS, including control establishment and NAVD 88 tie.",
    driver="Miami-Dade Chapter 24 · SFWMD ERP submittal requirements · FEMA floodplain reference",
),
dict(
    id="STM-05", bucket="STM", name="Geotechnical Investigation & Permeability Testing",
    type="Investigation", status="Not started",
    headline="Measure how fast this soil actually absorbs water, so the hydraulic model is built on site data rather than assumption.",
    context="South Florida drainage design lives or dies on infiltration rate and seasonal high water table. Both are site-specific and both are inputs the model cannot run without. Testing at a small number of representative locations, selected once we know where the system is, gives the model defensible numbers — and defensible numbers are what survive permit review.",
    scope=[
        "Select boring and test locations using the survey and CCTV results, targeting proposed exfiltration and retention areas.",
        "Advance soil borings with continuous sampling and classification.",
        "Perform in-situ permeability testing using the Miami-Dade accepted method to establish the hydraulic conductivity value.",
        "Establish the seasonal high water table elevation at each location.",
        "Deliver a geotechnical report with design-ready parameters, signed and sealed.",
    ],
    deliverables=[
        "Signed and sealed geotechnical report",
        "Hydraulic conductivity values by location",
        "Seasonal high water table elevations",
        "Design parameter summary issued to the modelling team",
    ],
    pred=["STM-04"], party="APAS · Geotechnical engineer",
    role="MANAGED", fee="COST_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Geotechnical subcontract procured and administered by APAS. Number of test locations set in the proposal; additional locations priced per unit.",
    driver="Miami-Dade Chapter 24 exfiltration trench design criteria · SFWMD ERP",
),
dict(
    id="STM-06", bucket="STM", name="Retention Pond Survey",
    type="Survey", status="Not started",
    headline="Establish the pond's real shape, depth and current storage volume — above and below the waterline.",
    context="The retention pond is the property's primary stormwater storage asset, and we do not know its current capacity. Sediment accumulates slowly and silently; the pond looks unchanged from the bank while the storage inside it disappears. A bathymetric and topographic survey establishes what capacity exists today against what capacity was permitted, and that difference is the dredging case.",
    scope=[
        "Topographic survey of the pond banks, top of bank, side slopes and control structure.",
        "Bathymetric survey of the pond bottom on a defined grid, capturing the sediment surface.",
        "Probe to establish the depth of accumulated sediment and the original design bottom where recoverable.",
        "Survey and document the outfall control structure, including weir elevations and orifice dimensions.",
        "Compute the current stage-storage relationship and compare it against the permitted design storage.",
    ],
    deliverables=[
        "Pond topographic and bathymetric survey",
        "Sediment thickness map",
        "Current versus permitted stage-storage curve",
        "Control structure documentation",
    ],
    pred=["STM-04"], party="APAS · Professional Surveyor & Mapper",
    role="MANAGED", fee="COST_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Survey subcontract procured and administered by APAS, including boat or float-based bathymetric collection.",
    driver="SFWMD ERP permitted storage volume · Miami-Dade Chapter 24",
),
dict(
    id="STM-07", bucket="STM", name="Digital Terrain Model & Dredge Volume Determination",
    type="Analysis", status="Not started",
    headline="Turn the pond survey into a three-dimensional model and compute exactly how much material has to come out.",
    context="Dredging is priced by the cubic yard. Without a computed volume, the owner is exposed to open-ended quantities and change orders. A digital terrain model built from the survey produces a defensible quantity before anyone mobilises, and it becomes the basis for the bid, for the disposal estimate, and for measuring the contractor's completion.",
    scope=[
        "Build a digital terrain model of the existing sediment surface and of the target design bottom.",
        "Compute cut volumes between the two surfaces, with contingency banding.",
        "Produce dredge limit drawings and target elevation contours for the contractor.",
        "Establish the measurement and verification method for confirming completion and final quantities.",
        "Model the post-dredge stage-storage curve to confirm the storage volume recovered.",
    ],
    deliverables=[
        "Digital terrain model (existing and design surfaces)",
        "Computed dredge volume with contingency band",
        "Dredge limit and target elevation drawings",
        "Measurement and verification protocol",
        "Post-dredge stage-storage curve",
    ],
    pred=["STM-06"], party="APAS",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services — analysis and drawing production from existing survey data.",
    driver="SFWMD ERP storage restoration · construction quantity basis",
),
dict(
    id="STM-08", bucket="STM", name="Dredged Material Characterization, Profiling & Disposal",
    type="Environmental · Construction", status="Not started",
    headline="Sample and profile the sediment before it moves, so it goes to a facility that will legally accept it.",
    context="This has to happen before dredging, not after. Sediment from a pond adjacent to industrial neighbours cannot be assumed clean. Waste profiling determines the disposal pathway and the disposal cost, and those two facts can swing the dredging budget by a wide margin. Profiling first also protects the owner from the worst case in this kind of work: material excavated, staged on site, and then found to be unacceptable at the receiving facility.",
    scope=[
        "Develop a sampling and analysis plan appropriate to the pond and the surrounding land uses.",
        "Collect representative sediment samples across the pond footprint and at depth.",
        "Laboratory analysis for the contaminants of concern indicated by the adjacent land uses, including metals and petroleum constituents.",
        "Prepare the waste profile and obtain written acceptance from the receiving facility before dredging begins.",
        "Determine the disposal pathway and confirm hauling, manifesting and chain of custody requirements.",
        "Manage transport and disposal during dredging, with full manifest documentation retained for the compliance record.",
    ],
    deliverables=[
        "Sampling and analysis plan",
        "Laboratory analytical results",
        "Approved waste profile and written facility acceptance",
        "Disposal pathway determination memo",
        "Complete manifest and chain of custody file",
    ],
    pred=["STM-06"], party="APAS · Environmental consultant · Licensed hauler",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="APAS professional services on a fixed fee; laboratory, hauling and disposal procured and administered by APAS. Disposal cost is governed by the characterization result — which is precisely why it is determined early and cheaply.",
    driver="Miami-Dade DERM · FDEP solid waste rules · Chapter 62-701 F.A.C.",
),
dict(
    id="STM-09", bucket="STM", name="Retention Pond Dredging",
    type="Construction", status="Not started",
    headline="Remove the accumulated sediment and restore the pond to its design storage volume.",
    context="This is the physical recovery of storage capacity the property has lost to sedimentation. It is a construction project with a measured quantity, a defined target elevation and a verification survey at completion — not an open-ended clean-out.",
    scope=[
        "Procure and contract the dredging work against the computed volume and dredge limit drawings.",
        "Mobilise, install turbidity and erosion controls, and establish the dewatering and staging area.",
        "Dredge to the design bottom elevation within the defined limits.",
        "Dewater the removed material to a transportable moisture content.",
        "Restore banks and side slopes; stabilise and re-vegetate disturbed areas, including the littoral zone.",
        "Post-dredge verification survey confirming target elevations and the storage volume recovered.",
    ],
    deliverables=[
        "Executed dredging contract against measured quantities",
        "Turbidity monitoring records",
        "Post-dredge verification survey",
        "Storage volume recovery certification",
        "Bank restoration and stabilisation completion",
    ],
    pred=["STM-07", "STM-08"], party="APAS · Dredging contractor",
    role="MANAGED", fee="COST_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Construction subcontract procured and administered by APAS against the measured quantity from STM-07. Disposal handled under STM-08.",
    driver="SFWMD ERP · Miami-Dade DERM dewatering and turbidity permits · Consent Order",
),
dict(
    id="STM-10", bucket="STM", name="Comprehensive Hydrologic & Hydraulic Model",
    type="Analysis", status="Not started",
    headline="Model the whole property against the 5-year, 25-year and 100-year storms and find out where the water goes.",
    context="This is the analytical core of the stormwater bucket. Every field project before it exists to feed this model, and every design project after it is dictated by its results. It answers the question the owner actually cares about: in a real storm, does water enter the buildings, and are the streets passable. Modelling three return periods separates a nuisance event from a life-safety event and tells us which improvements are required rather than merely desirable.",
    scope=[
        "Build the model from the survey base map, the CCTV network geometry, the geotechnical permeability values and the pond stage-storage curve.",
        "Calibrate against observed flooding history on the property where records or resident reports exist.",
        "Run the 5-year, 25-year and 100-year design storms for the applicable durations.",
        "Evaluate two protection criteria explicitly and separately: finished floor elevation protection for every building, and roadway passability for emergency access.",
        "Identify every deficiency — undersized pipes, insufficient storage, inadequate pumping, low points and overland flow paths.",
        "Test improvement scenarios and quantify the flood-risk reduction each one buys.",
        "Determine whether the pond and pipe network alone can meet the required level of service, or whether supplemental features are needed.",
        "Write the results into the Stormwater Management Plan as the governing design basis.",
    ],
    deliverables=[
        "Calibrated hydrologic and hydraulic model",
        "Flood maps and inundation depths for each return period",
        "Finished floor and roadway risk assessment by building and by street",
        "Deficiency register with hydraulic cause identified",
        "Improvement scenario comparison with risk reduction quantified",
        "Determination on the need for supplemental features",
    ],
    pred=["STM-04", "STM-05", "STM-06"], party="APAS · Engineer of Record",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services — model build, calibration, three-storm analysis and scenario testing.",
    driver="Miami-Dade Chapter 24 · SFWMD ERP · FEMA · NPDES MS4 · Consent Order",
),
dict(
    id="STM-11", bucket="STM", name="Stormwater Lift Station — Adequacy Assessment, Siting & Design",
    type="Design", status="Not started",
    headline="Determine whether the pumping capacity serving the pond is adequate, whether it is in the right place, and design what it should be.",
    context="A retention pond only performs if what leaves it can leave fast enough. This project evaluates the existing pumping arrangement against modelled demand, tests whether its location relative to the pond is hydraulically correct, and produces a design for whatever the answer requires — rerating, relocating, or replacing.",
    scope=[
        "Assess the existing lift station: condition, capacity, controls, power supply and reliability.",
        "Evaluate its location relative to the retention pond and to the modelled inflow points.",
        "Determine required firm capacity against the modelled design storms.",
        "Evaluate siting alternatives where relocation is indicated.",
        "Produce design drawings and specifications for the selected configuration, including wet well, pumps, controls, standby power and telemetry.",
        "Establish the permitting pathway and prepare permit-ready documents.",
    ],
    deliverables=[
        "Adequacy and condition assessment report",
        "Siting alternatives evaluation with recommendation",
        "Signed and sealed design drawings and specifications",
        "Permit-ready submittal package",
    ],
    pred=["STM-10"], party="APAS · Engineer of Record",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services — assessment, siting and design. Construction proposed separately once the design is set.",
    driver="SFWMD ERP · Miami-Dade Chapter 24 · flood protection level of service",
),
dict(
    id="STM-12", bucket="STM", name="Retention Pond Design & Reconfiguration",
    type="Design", status="Not started",
    headline="Design the pond to the storage volume the model requires, not the volume it happens to have.",
    context="Once the model states the storage volume this property needs in order to be protected in a design storm, the pond has to be designed to deliver it. That may mean deepening, expanding the footprint, reshaping side slopes for safety and maintenance access, or rebuilding the control structure.",
    scope=[
        "Design the pond to the target storage volume and stage-storage relationship established by the hydraulic model.",
        "Design side slopes, safety shelf, littoral zone and maintenance access.",
        "Design the outfall control structure — weir, orifice and discharge rate — to the permitted allowable discharge.",
        "Integrate with the lift station design and confirm combined performance.",
        "Prepare permit-ready drawings, calculations and specifications.",
    ],
    deliverables=[
        "Signed and sealed pond design drawings",
        "Stage-storage-discharge calculations",
        "Control structure design",
        "Permit submittal package",
    ],
    pred=["STM-10"], party="APAS · Engineer of Record",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services — design and permitting. Construction proposed separately once quantities are set.",
    driver="SFWMD ERP · Miami-Dade Chapter 24 allowable discharge rate",
),
dict(
    id="STM-13", bucket="STM", name="Site Regrading & Recontouring — Design, Permit & Construct",
    type="Design · Permit · Construct", status="Not started",
    headline="Reshape the ground so that water goes where the model says it should go.",
    context="The model will identify low points, reverse slopes and blocked overland flow paths that no pipe can fix. Regrading is how a property is made to drain by gravity before any mechanical system is asked to help. This is the largest construction item in the program and is scoped, phased and priced directly from the model results.",
    scope=[
        "Design regrading and recontouring to achieve the drainage patterns and hydraulic capacity established by the model.",
        "Set finished floor protection and roadway crown elevations to the adopted level of service.",
        "Design conveyance improvements — swales, inlets, pipe upsizing — where the model identifies capacity deficiency.",
        "Permit through Miami-Dade DERM, SFWMD and the City of Opa-Locka.",
        "Phase construction to maintain resident access, parking and emergency vehicle circulation throughout.",
        "Construct, with survey verification of finished grades against design.",
        "Restore paving, landscaping and site features.",
    ],
    deliverables=[
        "Signed and sealed grading and drainage drawings",
        "Approved permits",
        "Phased construction plan with resident access maintained",
        "Constructed improvements with as-built survey verification",
        "Record drawings issued into the Stormwater Management Plan",
    ],
    pred=["STM-10"], party="APAS · Engineer of Record · General contractor",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Design and permitting on a fixed fee; construction procured and administered by APAS. Scope is entirely determined by the model, so the construction proposal follows STM-10.",
    driver="Miami-Dade Chapter 24 · SFWMD ERP · City of Opa-Locka · Consent Order · FEMA",
),
dict(
    id="STM-14", bucket="STM", name="Supplemental Stormwater Features — Exfiltration Trench & the Second Retention Area",
    type="Investigation · Design · Construct", status="Conditional",
    headline="If the model says the pond and pipes are not enough, add capacity — and finally settle the question of the second retention area.",
    context="This project is deliberately conditional. It is triggered only if the hydraulic model demonstrates that the primary system cannot meet the required level of service. Two options are on the table. The first is an exfiltration trench system, which is the standard Miami-Dade answer and depends directly on the permeability values from the geotechnical work. The second is the second retention area — a feature everybody on this property references and nobody has located. That ambiguity is itself a liability, and this project closes it: we either find it, confirm it, and restore it to function, or we establish on the record that it does not exist.",
    scope=[
        "Locate and confirm the second retention area through records, historical aerials, geophysical survey and field investigation.",
        "If found: assess its condition, permitted status and residual storage capacity, and determine whether restoration is viable and cost-effective.",
        "If not found: document the investigation and formally close the question so it stops appearing as an open assumption in every future analysis.",
        "Design an exfiltration trench system sized to the residual storage deficit, using the measured hydraulic conductivity from the geotechnical work.",
        "Compare the two options on capacity delivered, cost, permitability and long-term maintenance burden.",
        "Permit and construct the selected option.",
    ],
    deliverables=[
        "Second retention area investigation report — located and assessed, or formally closed out",
        "Exfiltration trench design and calculations",
        "Options comparison with recommendation",
        "Permits and constructed improvements",
    ],
    pred=["STM-10"], party="APAS · Engineer of Record · Contractor",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Conditional — proposed only if the model identifies a residual storage deficit. Investigation and design on a fixed fee; construction procured and administered by APAS.",
    driver="Miami-Dade Chapter 24 exfiltration criteria · SFWMD ERP",
),
dict(
    id="STM-15", bucket="STM", name="Stormwater Operations Plan",
    type="Operations · Documentation", status="Not started",
    headline="Turn the plan into a running operation — the same way the sewer extension was operationalized.",
    context="A management plan describes the system. An operations plan runs it. This is the document that survives staff turnover: who inspects what, how often, what triggers a response, what gets recorded, and what gets reported to whom. It follows exactly the model already proven on the sewer side of this property.",
    scope=[
        "Define routine inspection and maintenance procedures for every asset class — catch basins, pipes, pond, control structure, lift station and any supplemental features.",
        "Set inspection frequencies, cleaning cycles and sediment removal triggers, so storage loss is caught early rather than rediscovered in a decade.",
        "Establish pre-storm readiness and post-storm response procedures.",
        "Define the regulatory reporting calendar and the responsible party for each submittal.",
        "Establish record-keeping, evidence retention and the annual system condition review.",
        "Define performance monitoring, alarm thresholds and escalation paths.",
        "Build the operating record into ProjOS with scheduled tasks, evidence capture and automatic compliance reporting.",
    ],
    deliverables=[
        "Stormwater Operations Plan",
        "Inspection and maintenance schedule by asset class",
        "Pre-storm and post-storm response procedures",
        "Regulatory reporting calendar with named responsibility",
        "ProjOS operating record with scheduled tasks and evidence capture",
        "Staff training and handover",
    ],
    pred=["STM-13"], party="APAS",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services — plan development, ProjOS configuration and staff handover.",
    driver="NPDES MS4 operations and maintenance · Consent Order · Miami-Dade Chapter 24",
),

# ============================== SEWER =========================================
dict(
    id="SWR-01", bucket="SWR", name="Conveyance & Close-Out to the City of Opa-Locka",
    type="Administrative / Engineering Coordination", status="In progress",
    headline="Transfer the completed sewer extension to the City so it becomes the City's asset to own, operate and maintain.",
    context="This is an administrative project, and it deserves to be run like a project — it has a defined scope, a set of dependencies on five outside parties, and a fee. It is not a punch list item. Until the City formally accepts the system, the owner continues to hold the asset, the maintenance duty and the warranty exposure.",
    scope=[
        "Run the City of Opa-Locka Utilities Conveyance Checklist to completion, item by item, with a named owner and a date against every line.",
        "Coordinate the Engineer of Record deliverables: signed and sealed record drawings, infiltration and exfiltration certification, Engineer's Final Payment Confirmation, FDEP sewer certification, General Permit and In-Service Letter, latitude and longitude detail sheet, and the record-drawing disk.",
        "Coordinate the surveyor's signed and sealed as-built survey (PDF plus editable CAD) and reconcile it against the record drawings.",
        "Coordinate the contractor's CCTV video of the constructed gravity sewer, the Sewer Report and the Master Utility Sheet, plus field completion and restoration for the City's preliminary inspection.",
        "Close the contractor package: punch list completion, final lien waivers, material certifications, test results, permit close-outs, and asphalt and sod final quantities.",
        "Execute and file the three twelve-month warranties by building group — Building 3 South with Building 4; Building 5 with Building 6; and Building 3 North.",
        "Support owner's counsel on the legal and security items: Attorney's and Owner's Affidavits, Warranty Deed and Bill of Sale, UCC subordination, and the Utilities Performance Security.",
        "Assemble, transmit and track the acceptance package through City review to written acceptance.",
    ],
    deliverables=[
        "Completed Utilities Conveyance Checklist with evidence attached to every line",
        "Transmittal package to the City of Opa-Locka",
        "Executed warranty set (three building groups)",
        "Written City acceptance and asset transfer confirmation",
        "Retainage release documentation per the contract schedule",
    ],
    pred=[], party="APAS (lead) · Engineer of Record · Surveyor · Contractors · Owner's counsel",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services for coordination and package assembly. Excludes the Utilities Performance Security, the final-obligations cash bond, and City review fees, all of which sit with the owner.",
    driver="City of Opa-Locka Utilities Conveyance Checklist · Miami-Dade DERM · FDEP General Permit · Prime Contract PC-01",
),
dict(
    id="SWR-02", bucket="SWR", name="Master Effluent Flow Meter at the Property Discharge Point",
    type="Design · Permit · Construct", status="Not started",
    headline="Install a permanent flow meter where wastewater leaves the property, so total discharge to the City pump station is a measured fact.",
    context="Glorieta Gardens is the largest single discharger into this pump station. Today, the volume leaving the property is inferred rather than measured. That is a problem in three directions at once: it makes infiltration and inflow impossible to isolate, it leaves billing and capacity allocation open to dispute, and it means any compliance question about what we discharge has no defensible answer. A meter at the exit resolves all three.",
    scope=[
        "Confirm the single point of discharge from the property to the City's collection system and verify there is no secondary or bypass connection.",
        "Design a permanent metering structure — vault or dedicated manhole — sized and located for safe, permanent access and for accurate hydraulic conditions.",
        "Select and specify the metering technology appropriate to the flow regime, with redundancy on the primary reading.",
        "Design telemetry and continuous data logging so the record is automatic, timestamped and retrievable, not a monthly clipboard reading.",
        "Permit through the City of Opa-Locka and Miami-Dade DERM as required.",
        "Construct, commission and field-calibrate; establish the certified accuracy baseline.",
        "Run a baseline infiltration and inflow study using the new meter — diurnal flow curves and wet-weather response — to quantify how much of what we discharge is groundwater and rainwater rather than sanitary flow.",
        "Integrate the meter data feed into ProjOS for continuous monitoring and exception alerting.",
    ],
    deliverables=[
        "Signed and sealed design drawings and specifications",
        "Approved permits",
        "Constructed and commissioned metering station",
        "Calibration certificate and accuracy baseline",
        "Baseline I&I report with wet-weather response curves",
        "Live data feed into ProjOS",
    ],
    pred=["SWR-01"], party="APAS · Engineer of Record · Contractor · City of Opa-Locka",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Design, permitting and commissioning on a fixed fee; structure, meter, telemetry and installation procured and administered by APAS.",
    driver="City of Opa-Locka wastewater discharge accounting · DERM · FDEP · I&I reduction",
),

# ============================== WATER =========================================
dict(
    id="WTR-01", bucket="WTR", name="Water & Sewer Records and File Assessment",
    type="Investigation", status="Scope approved", flag="SCOPE APPROVED",
    headline="Review every available file to establish what is documented about the water and sewer systems on this property.",
    context="This was originally discussed as a wastewater file review. It has to be wider. To know where our water pipes are, we need to review all of the files — every utility record, every permit, every plan set, from every source that might hold one. The expanded scope is a modest increase in effort against a substantial increase in what we recover. Scope is approved; a short proposal follows for signature and becomes the basis of the work.",
    scope=[
        "Search and retrieve from the City of Opa-Locka, Miami-Dade Water and Sewer Department, DERM, RER and the building department.",
        "Pursue original developer, architect and engineer record sets, plats, easements and utility agreements.",
        "Retrieve permit history: water main extensions, service connections, meter installations and backflow device records.",
        "Review historical aerials and prior construction documents for evidence of utility modifications over time.",
        "Assess each document for reliability — sealed as-built, permit set, sketch or hearsay — and rate it accordingly.",
        "Produce a records inventory and a gap register identifying exactly what remains unknown.",
    ],
    deliverables=[
        "Records inventory with source and reliability rating",
        "Gap register: what is documented and what is not",
        "Recommendation memo on the field verification path",
    ],
    pred=[], party="APAS",
    role="SELF", fee="LS", auth="APPROVED", budget="$3,000 — Lump Sum",
    budget_note="Lump sum, scope approved. Covers the expanded all-utilities review. Agency records request and reproduction fees passed through at cost.",
    driver="Miami-Dade WASD · Chapter 24 · City of Opa-Locka utility records",
),
dict(
    id="WTR-02", bucket="WTR", name="Water Distribution Field Verification & As-Built Development",
    type="Survey · Investigation", status="Not started",
    headline="Establish where the water pipes actually are — from the records if they hold up, from the field if they do not.",
    context="This project has two paths and the file assessment picks which one. If the records are good, we field-verify them at control points and produce an as-built from documentation. If they are not — and on a property of this age that is the likelier outcome — we run a full field verification survey. Either way, the deliverable is the same: a signed, sealed as-built showing where the water system is, so that any future modification is planned against fact rather than assumption.",
    scope=[
        "Path A — records adequate: field-verify at control points, reconcile against the documentation, and produce an as-built from the record set.",
        "Path B — records inadequate: full field verification survey using electromagnetic pipe locating and ground-penetrating radar across the site.",
        "Survey and elevate all surface appurtenances: valves, hydrants, meters, backflow devices and service points.",
        "Pothole at critical locations and at points of future work to confirm horizontal position, depth, diameter and material.",
        "Reconcile all field data against whatever records exist and resolve every conflict.",
        "Produce a signed and sealed water system as-built in PDF and editable CAD.",
        "Identify unknown, abandoned or unmapped lines and flag them for follow-up.",
    ],
    deliverables=[
        "Signed and sealed water distribution as-built",
        "Editable CAD (DWG/DXF)",
        "Valve, hydrant, meter and appurtenance schedule",
        "Potholing records with depth, diameter and material confirmed",
        "Register of unknown or abandoned lines",
    ],
    pred=["WTR-01"], party="APAS · Surveyor · Subsurface utility locating contractor",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Proposed against whichever path the file assessment establishes. APAS professional services on a fixed fee; survey and locating procured and administered by APAS.",
    driver="Miami-Dade Chapter 24 · WASD standards · Sunshine 811 · construction risk mitigation",
),
dict(
    id="WTR-03", bucket="WTR", name="Water Meter Box Program — Design, Permit & Construct",
    type="Design · Permit · Construct", status="Not started",
    headline="Design, permit and build the meter boxes; the City of Opa-Locka installs its meters into them.",
    context="The division of responsibility here is clean and worth stating plainly: we deliver the boxes, the services and the settings, ready and inspected. The City brings and installs its own meters. Getting that handoff sequenced and documented is most of the work — an unready box on the day the City arrives costs weeks.",
    scope=[
        "Determine meter count, sizing and locations from the as-built and from the service configuration.",
        "Design meter box installations to City of Opa-Locka and Miami-Dade WASD standards, including box, setting, service piping and appurtenances.",
        "Locate boxes for permanent access, safe reading and protection from vehicle traffic.",
        "Permit through the City of Opa-Locka and WASD.",
        "Construct with resident water service maintained; phase and notice all interruptions.",
        "Coordinate City meter installation: schedule, inspect, witness and document.",
        "Verify and document every installation, and record final meter numbers against service addresses.",
    ],
    deliverables=[
        "Meter schedule with sizing and locations",
        "Signed and sealed design drawings",
        "Approved permits",
        "Constructed and inspected meter boxes",
        "City meter installation coordination and completion record",
        "Meter number to service address register",
    ],
    pred=["WTR-02"], party="APAS · Engineer of Record · Contractor · City of Opa-Locka",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Design and permitting on a fixed fee; construction procured and administered by APAS against the meter count established in WTR-02. Excludes City meters and City fees.",
    driver="City of Opa-Locka · Miami-Dade WASD standards · Chapter 24",
),
dict(
    id="WTR-04", bucket="WTR", name="Backflow Prevention Program — Design, Permit & Install",
    type="Design · Permit · Construct", status="Not started",
    headline="Install backflow prevention at every required connection and enrol the devices in certified annual testing.",
    context="Backflow prevention is a cross-connection control requirement, and it is one of the compliance items most likely to generate a violation quietly — because the obligation is not just installing the device, it is testing and certifying it every year, forever. This project delivers both the installation and the standing testing program.",
    scope=[
        "Survey all connections and determine the required device type and hazard classification at each.",
        "Design installations to City of Opa-Locka and WASD standards, with permanent access and traffic protection.",
        "Permit through the City and WASD.",
        "Procure, install, and commission all devices.",
        "Perform initial certification testing by a certified tester and file the results with the City.",
        "Enrol every device in the annual testing and certification program, with the schedule and evidence capture built into ProjOS.",
        "Build the device register: location, type, serial number, installation date and test history.",
    ],
    deliverables=[
        "Cross-connection hazard survey and device schedule",
        "Signed and sealed design drawings and permits",
        "Installed and commissioned devices",
        "Initial certification test reports filed with the City",
        "Device register with full test history in ProjOS",
        "Annual testing program with scheduled reminders",
    ],
    pred=["WTR-02"], party="APAS · Engineer of Record · Contractor · Certified backflow tester",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Design and permitting on a fixed fee; devices, installation and initial certification procured and administered by APAS. Annual testing thereafter carried under ongoing compliance services.",
    driver="Miami-Dade Chapter 24 cross-connection control · City of Opa-Locka · F.A.C. 62-555 · Safe Drinking Water Act",
),
dict(
    id="WTR-05", bucket="WTR", name="Irrigation Well — Permit, Drill & Commission",
    type="Design · Permit · Construct", status="Not started",
    headline="Put in an irrigation well to serve the common areas, and take that demand off the potable system.",
    context="Irrigating common areas with treated potable water is expensive and, at this property's scale, unnecessary. An irrigation well moves that demand to a dedicated source. It reduces the potable bill directly, it removes irrigation volume from the meters we are about to install, and it separates a non-potable use from the drinking water system — which is a cross-connection benefit as well as a cost one.",
    scope=[
        "Hydrogeologic siting: aquifer selection, expected yield, water quality and required setbacks from sanitary and environmental features.",
        "Coordinate siting explicitly with the environmental monitoring well program so the two do not conflict.",
        "Permit through Miami-Dade DERM and SFWMD, including water use authorisation.",
        "Drill, develop and test the well; confirm yield and water quality.",
        "Install pump, controls, and above-ground equipment with backflow protection.",
        "Design and construct the irrigation distribution to the common areas, with zoning and controller.",
        "Commission, test and hand over with an operations and maintenance manual.",
    ],
    deliverables=[
        "Hydrogeologic siting report",
        "DERM and SFWMD permits",
        "Completed well with yield and water quality test results",
        "Pump, controls and distribution system installed and commissioned",
        "Operations and maintenance manual",
        "Potable demand reduction baseline",
    ],
    pred=["WTR-02"], party="APAS · Hydrogeologist · Licensed well contractor",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Siting, permitting and construction management on a fixed fee; drilling, pump, controls and distribution procured and administered by APAS.",
    driver="Miami-Dade DERM well permit · SFWMD water use permit · Chapter 24 cross-connection control",
),
dict(
    id="WTR-06", bucket="WTR", name="Non-Revenue Water Assessment & Water Balance",
    type="Analysis · Operations", status="For discussion", flag="FOR DISCUSSION", flag_kind="discuss",
    headline="Find out how much of the water this property buys never reaches a bill — and how much of that is recoverable.",
    context="This is a small project and it is not yet scoped, because it should be talked through first. The question it answers is simple and, at this property's scale, financially material: the City meters what it delivers to Glorieta Gardens, and the property pays for that volume in full. How much of it actually reaches a resident, and how much disappears on the way? The gap has three components — water that leaked out of the pipes, water that was used but measured badly, and water that was used legitimately and never billed. Each has a different fix and a very different cost, and the audit tells you which one you have before anyone spends money chasing the wrong one. It also happens to sit perfectly in the sequence: the meter boxes are about to be installed and the irrigation well will pull a large unmetered use off the potable system, which means the property is about to have the data this analysis needs for the first time.",
    scope=[
        "Establish the system input volume from the City's master metering and billing history, and verify the accuracy of the meter producing that number.",
        "Assemble billed consumption from the meter records and reconcile it against the input volume over a defined audit period.",
        "Build the water balance to the AWWA M36 standard, separating unbilled authorized consumption from apparent losses and real losses.",
        "Quantify apparent losses: meter under-registration by age and size, data handling and billing gaps, and any unauthorized or unrecorded connections.",
        "Quantify real losses and compute the Infrastructure Leakage Index, so the result can be compared against the technical minimum for a system of this size rather than against a generic benchmark.",
        "Run a minimum night flow analysis using continuous logging, since night-time residual flow is the most direct available indicator of leakage.",
        "Evaluate whether dividing the site into district metered areas would be worthwhile, so future losses can be localised to a block rather than to the property as a whole.",
        "Quantify the annual dollar value of the loss at the City's current rate, and rank the recovery measures by cost against recoverable volume.",
        "Establish an ongoing tracking method in ProjOS so the figure is monitored continuously rather than rediscovered every few years.",
    ],
    deliverables=[
        "AWWA M36 water balance for the audit period",
        "Non-revenue water volume and percentage, with the dollar value at current rates",
        "Apparent versus real loss split with the basis for each",
        "Infrastructure Leakage Index",
        "Minimum night flow analysis",
        "Ranked loss-recovery recommendations with cost against recoverable volume",
        "Ongoing non-revenue water tracking in ProjOS",
    ],
    pred=["WTR-01"], party="APAS",
    role="SELF", fee="LS", auth="DISCUSS", budget=TBD,
    budget_note="Not yet scoped. APAS would like to discuss the objective and the audit period with the owner before proposing anything. A preliminary balance can be built from existing billing records; resolution improves substantially once WTR-03 metering is in and WTR-05 has taken irrigation off the potable system.",
    driver="Owner operating cost · AWWA M36 · City of Opa-Locka billing reconciliation · water conservation",
),

# ============================== ENVIRONMENTAL =================================
dict(
    id="ENV-01", bucket="ENV", name="Adjacent Property Environmental File Review & Plume Assessment",
    type="Investigation", status="Not started",
    headline="Review the environmental history of every property surrounding this one — the junkyards above all — and determine where contamination could be coming from.",
    context="This is the scoping project for the entire environmental bucket, and it has to come first. The monitoring well locations, the analytical parameter list and the sampling frequency all follow from what this review finds. Placing wells before knowing what we are looking for and where it would come from means paying for wells in the wrong places, testing for the wrong things.",
    scope=[
        "Identify every adjacent and nearby property on all four sides and establish its current and historical use.",
        "Focus the review on the junkyard and salvage operations, which are the most probable sources.",
        "Search the regulatory databases: DERM, FDEP and EPA records — RCRA, CERCLIS, petroleum storage, dry cleaning and industrial waste files.",
        "Retrieve and review enforcement history, contamination assessment reports and remediation records for each source property.",
        "Review historical aerials, Sanborn maps and city directories to reconstruct site use over time.",
        "Establish the contaminants of concern based on documented use and documented releases.",
        "Determine the groundwater gradient and flow direction across the property from regional and site data.",
        "Model probable plume vectors: which boundaries are downgradient of which sources, and where migration onto Glorieta Gardens would first appear.",
    ],
    deliverables=[
        "Adjacent property environmental history report",
        "Contaminants of concern list with the documented basis for each",
        "Groundwater flow direction and gradient determination",
        "Plume vector analysis with probable migration pathways",
        "Monitoring well siting recommendation and analytical parameter list",
    ],
    pred=[], party="APAS · Environmental consultant",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services. Agency file review fees and database search costs passed through at cost.",
    driver="Miami-Dade DERM Chapter 24 · FDEP Chapter 62-780 F.A.C. · owner due diligence",
),
dict(
    id="ENV-02", bucket="ENV", name="Boundary Monitoring Well Network — Design & Installation",
    type="Design · Permit · Construct", status="Not started",
    headline="Install a monitoring well network on the property boundaries, positioned by the plume analysis.",
    context="The working assumption is a minimum of two wells on each side — four sides, so at least eight wells, with the final count and placement set by the file review. The purpose is specific and worth being precise about: these wells exist to detect contamination arriving from off-site, so that if a neighbour's plume has reached this property, the owner knows it first and documents it first.",
    scope=[
        "Finalise well count, locations and screen intervals from the plume vector analysis, with upgradient wells for background and downgradient wells for detection.",
        "Design each well to DERM standards: construction, screen interval, filter pack, seal and surface completion.",
        "Locate wells for permanent access and protection from vehicles and site operations.",
        "Coordinate placement with the irrigation well siting so the two programs do not interfere.",
        "Permit through Miami-Dade DERM.",
        "Drill, install, develop and survey each well; establish measuring point elevations to NAVD 88.",
        "Conduct the initial round of groundwater elevation measurements and confirm the actual flow direction against the predicted gradient.",
        "Build the well network register into ProjOS with location, construction detail and sampling history.",
    ],
    deliverables=[
        "Monitoring well network design and siting plan",
        "DERM well permits",
        "Installed, developed and surveyed wells with completion logs",
        "Measuring point elevations tied to NAVD 88",
        "Confirmed groundwater flow direction from measured elevations",
        "Well network register in ProjOS",
    ],
    pred=["ENV-01"], party="APAS · Environmental consultant · Licensed well contractor",
    role="MANAGED", fee="COST_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Drilling and installation subcontract procured and administered by APAS. Well count and depth set by the plume analysis and confirmed in the proposal.",
    driver="Miami-Dade DERM Chapter 24 monitoring well permit · FDEP Chapter 62-780 F.A.C.",
),
dict(
    id="ENV-03", bucket="ENV", name="Groundwater Sampling & Plume Behaviour Analysis",
    type="Monitoring · Analysis", status="Not started",
    headline="Sample the wells on a defined schedule and determine whether contamination is migrating onto the property.",
    context="A single sampling round tells you a concentration. A sequence of rounds tells you a direction and a trend, and direction and trend are what actually answer the question. This project establishes the baseline and then runs the recurring rounds needed to characterise plume behaviour — whether anything is arriving, from where, at what concentration, and whether it is getting worse.",
    scope=[
        "Prepare a sampling and analysis plan with the parameter list from the file review and DERM-acceptable methods.",
        "Conduct the baseline sampling round across the full network, with proper purging, field parameters and chain of custody.",
        "Laboratory analysis at a Florida-certified laboratory with full quality assurance and quality control.",
        "Conduct recurring rounds on the established frequency, with synoptic water level measurements each round.",
        "Evaluate the results against DERM and FDEP groundwater cleanup target levels.",
        "Analyse plume behaviour across rounds: presence, source attribution, concentration gradient and trend direction.",
        "Determine whether contamination is migrating onto Glorieta Gardens and whether any property component has been impacted.",
        "Maintain the full analytical record and trend dashboard in ProjOS.",
    ],
    deliverables=[
        "Sampling and analysis plan",
        "Baseline groundwater quality report",
        "Recurring round reports with laboratory data packages",
        "Plume behaviour and trend analysis",
        "Comparison against groundwater cleanup target levels",
        "Determination of off-site contaminant migration and property impact",
        "Analytical record and trend dashboard in ProjOS",
    ],
    pred=["ENV-02"], party="APAS · Environmental consultant · Certified laboratory",
    role="HYBRID", fee="LS_PLUS", auth="PROPOSED", budget=TBD,
    budget_note="Sampling, interpretation and reporting on a fixed fee per round; laboratory analysis procured and administered by APAS. Frequency set by the baseline result and proposed annually.",
    driver="Miami-Dade DERM · FDEP Chapter 62-780 F.A.C. groundwater cleanup target levels",
),
dict(
    id="ENV-04", bucket="ENV", name="Environmental Findings Report & Regulatory Strategy",
    type="Analysis · Strategy", status="Not started",
    headline="Convert the monitoring data into a decision: what the owner does next, and how it is presented to the City and to DERM.",
    context="Data does not protect the owner. A documented position built on data does. This project takes everything the investigation produced and turns it into a defensible finding, a recommended course of action, and a deliberate approach to the City of Opa-Locka and Miami-Dade DERM — on the owner's timing and in the owner's framing, rather than in response to somebody else's inquiry.",
    scope=[
        "Consolidate the file review, plume analysis, well installation and all sampling results into a single findings report.",
        "State the conclusion on off-site contaminant migration, with the evidentiary basis for it.",
        "Assess impacts, if any, on property components — soil, groundwater, utilities and structures.",
        "Evaluate the regulatory implications and the owner's obligations and protections under Chapter 24 and Chapter 62-780.",
        "Where a source is identified off-site, document the attribution to support the owner's position on responsibility.",
        "Recommend the course of action: no further action, continued monitoring, formal notification, or assessment and remediation.",
        "Develop the engagement strategy for the City of Opa-Locka and Miami-Dade DERM, including timing, framing and supporting documentation.",
        "Prepare the submittal package for whichever pathway is selected.",
    ],
    deliverables=[
        "Environmental findings report with stated conclusions",
        "Property impact assessment",
        "Source attribution documentation",
        "Recommended course of action with alternatives evaluated",
        "Regulatory engagement strategy for the City and DERM",
        "Submittal package for the selected pathway",
    ],
    pred=["ENV-03"], party="APAS · Environmental consultant · Owner's counsel",
    role="SELF", fee="LS", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee professional services. Any assessment or remediation that follows is separately scoped and proposed.",
    driver="Miami-Dade DERM Chapter 24 · FDEP Chapter 62-780 F.A.C. · owner liability position",
),
dict(
    id="ENV-05", bucket="ENV", name="Consent Order Close-Out",
    type="Compliance", status="Active obligation",
    headline="Drive every enumerated corrective action to documented completion and secure written termination of the Consent Order.",
    context="This is the outcome the whole program is organised around. A Consent Order does not expire — it closes when every corrective action is complete, documented and accepted in writing. Anything less leaves the obligation live and the property encumbered. This project tracks each enumerated action to evidence-backed completion and pursues the written release.",
    scope=[
        "Build the master compliance matrix: every enumerated corrective action, its requirement, its status, the evidence of completion and the responsible party.",
        "Map each corrective action to the program projects that satisfy it, so completion is traceable rather than asserted.",
        "Assemble the evidence file for every action: drawings, certifications, test results, permits, photographs and correspondence.",
        "Prepare and submit the periodic progress reports on the required cadence, and bring any missed reporting current.",
        "Manage regulator correspondence, inspections and requests for information.",
        "Identify and resolve every remaining gap between current status and full compliance.",
        "Prepare and submit the close-out request with the complete evidence package.",
        "Pursue written termination of the Consent Order and retain the release in the permanent record.",
    ],
    deliverables=[
        "Master compliance matrix mapped to program projects",
        "Complete evidence file for every corrective action",
        "Periodic progress reports, current",
        "Gap resolution plan",
        "Close-out submittal package",
        "Written Consent Order termination",
    ],
    pred=[], party="APAS · Owner's counsel · Regulators",
    role="SELF", fee="MONTHLY", auth="PROPOSED", budget=TBD,
    budget_note="Monthly professional services under an annual authorisation. Corrective action work itself sits in the technical buckets and is proposed separately.",
    driver="Consent Order enumerated corrective actions · FDEP · Miami-Dade DERM · NPDES MS4",
),
dict(
    id="ENV-06", bucket="ENV", name="Ongoing Regulatory Compliance Services",
    type="Recurring Services", status="Active",
    headline="Keep water, sewer and stormwater operating in conformance with their permits — local, county and state — without gaps.",
    context="Compliance is not a project that finishes. Permits renew, reports come due, devices need annual certification, and a missed deadline is a violation regardless of how well the underlying system is performing. This is the standing service that keeps every obligation on a calendar with a named owner and evidence attached — and, critically, keeps the property protected in flood and storm events, which is where regulatory risk and physical risk converge.",
    scope=[
        "Maintain the master permit and obligation register across the City of Opa-Locka, Miami-Dade DERM and RER, SFWMD and FDEP.",
        "Maintain the reporting calendar with lead-time alerts and a named responsible party on every submittal.",
        "Prepare and submit all periodic regulatory reports across water, sewer and stormwater.",
        "Manage permit renewals, modifications and condition compliance.",
        "Manage annual certifications, including backflow device testing.",
        "Serve as the point of contact for regulator inspections, inquiries and enforcement correspondence.",
        "Monitor regulatory change at local and state level and assess its impact on the property.",
        "Maintain flood-event readiness: pre-storm procedures, event response and post-event documentation and reporting.",
        "Maintain the complete compliance evidence record in ProjOS, audit-ready at any time.",
    ],
    deliverables=[
        "Master permit and obligation register",
        "Reporting calendar with named responsibility and lead-time alerts",
        "All periodic regulatory submittals, filed on time",
        "Permit renewals and annual certifications maintained",
        "Regulator correspondence file",
        "Flood-event readiness and response documentation",
        "Audit-ready compliance record in ProjOS",
    ],
    pred=[], party="APAS",
    role="SELF", fee="MONTHLY", auth="PROPOSED", budget=TBD,
    budget_note="Monthly professional services under an annual authorisation, scaling with the number of active permits and the reporting cadence.",
    driver="NPDES MS4 · FDEP · Miami-Dade DERM Chapter 24 · SFWMD ERP · City of Opa-Locka · Safe Drinking Water Act",
),

# ============================== PMO ===========================================
dict(
    id="PMO-01", bucket="PMO", name="Program & Project Management Services",
    type="Recurring Services", status="Active",
    headline="Day-to-day management of the crews on site and program-level control across all four buckets.",
    context="Thirty-one projects, four systems, three regulators and multiple contractors do not coordinate themselves. This is the function that holds scope and delivery under control across the whole program — and the function that keeps the owner from having to adjudicate between contractors.",
    scope=[
        "Day-to-day management of on-site crews and contractors: coordination, sequencing, quality and safety oversight.",
        "Program-level scope control across all buckets, with interface management where projects touch.",
        "Integrated master schedule with the cross-bucket dependency map maintained live.",
        "Procurement and administration of all specialty subcontracts.",
        "Change management, and change order review and negotiation.",
        "Pay application review, verification against installed work, and lien waiver control.",
        "Contract administration, including warranty tracking and retainage management.",
        "Permit tracking and agency coordination across the City, DERM, RER, SFWMD and FDEP.",
        "Owner reporting on a defined cadence: status, risk and schedule performance.",
        "Risk register maintained with mitigation owners and dates.",
    ],
    deliverables=[
        "Integrated master schedule, maintained live",
        "Monthly owner report: status, risk and schedule performance",
        "Change management log with full substantiation",
        "Reviewed and certified pay applications",
        "Risk register with mitigation owners",
        "Permit and agency coordination record",
    ],
    pred=[], party="APAS",
    role="SELF", fee="MONTHLY", auth="PROPOSED", budget=TBD,
    budget_note="Monthly professional services under an annual authorisation, scaling with the number of projects in active execution.",
    driver="Prime Contract PC-01 · owner governance",
),
dict(
    id="PMO-02", bucket="PMO", name="ProjOS Program Operating Record",
    type="Systems · Recurring", status="To be demonstrated",
    headline="Every project in this program instantiated in ProjOS — one operating record the owner can open at any time.",
    context="This is the layer worth seeing rather than reading about, and it is the one we should walk through live with R4. Each project in this document becomes a live object in ProjOS carrying its scope, deliverables, permits, documents and current status. The systems connect: the flow meter feeds live data, the compliance calendar drives alerts, the evidence file assembles itself as work is completed. The owner stops asking what the status is and starts looking at it.",
    scope=[
        "Instantiate all program projects in ProjOS with scope, deliverables, dependencies and approval status.",
        "Configure the five program buckets with roll-up reporting to a program-level dashboard.",
        "Connect live data: the sewer flow meter, groundwater monitoring results and stormwater performance monitoring.",
        "Build the compliance engine: permit register, reporting calendar, automated alerts and evidence capture.",
        "Establish the document control system, with every drawing, permit, certification and report attached to its project.",
        "Track every project proposal from issue through approval to completion, so the authorisation record is never in doubt.",
        "Configure owner-facing dashboards for status, schedule and risk.",
        "Build the operations layer for the stormwater, sewer and water operations plans, with scheduled tasks and completion evidence.",
        "Demonstrate the system live to R4 and configure access.",
    ],
    deliverables=[
        "All program projects live in ProjOS",
        "Program dashboard with bucket roll-up",
        "Live data integrations",
        "Compliance engine with automated alerts and evidence capture",
        "Document control system",
        "Proposal and approval tracking",
        "Owner-facing dashboards and access",
        "Live demonstration to R4",
    ],
    pred=[], party="APAS",
    role="SELF", fee="MONTHLY", auth="PROPOSED", budget=TBD,
    budget_note="Fixed-fee setup, then monthly administration and hosting under an annual authorisation.",
    driver="Owner governance · Consent Order evidence requirements · audit readiness",
),
]

ROLE_TEXT = {"SELF": SELF, "MANAGED": MANAGED, "HYBRID": HYBRID}
FEE_TEXT = {"LS": LS, "LS_PLUS": LS_PLUS, "COST_PLUS": COST_PLUS, "MONTHLY": MONTHLY}
FEE_SHORT = {"LS": "Lump sum", "LS_PLUS": "Lump sum + cost plus 20%",
             "COST_PLUS": "Cost plus 20%", "MONTHLY": "Monthly"}
ROLE_SHORT = {"SELF": "Self-perform", "MANAGED": "Managed", "HYBRID": "Hybrid"}
AUTH_TEXT = {"PROPOSED": PROPOSED, "APPROVED": APPROVED, "DISCUSS": DISCUSS}
