import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, LockKeyhole, Plus, Save, Settings2, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { requireTenantId } from '@/lib/tenant';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

function useReadinessSettings() {
  const qc = useQueryClient();
  const query = useQuery({
    queryKey: ['contractor-readiness', 'settings'],
    queryFn: async () => {
      const { data: templateId, error: ensureError } = await (supabase.rpc as any)('ensure_default_contractor_template');
      if (ensureError) throw ensureError;
      const [template, items, policy] = await Promise.all([
        supabase.from('contractor_requirement_templates' as any).select('*').eq('id', templateId).single(),
        supabase.from('contractor_requirement_items' as any).select('*').eq('template_id', templateId).order('sort_order'),
        supabase.from('contractor_readiness_policies' as any).select('*').eq('scope_type', 'workspace').maybeSingle(),
      ]);
      if (template.error) throw template.error; if (items.error) throw items.error; if (policy.error) throw policy.error;
      return { template: template.data as any, items: (items.data ?? []) as any[], policy: policy.data as any };
    },
  });
  const updateItem = useMutation({ mutationFn: async ({ id, patch }: any) => { const { error } = await supabase.from('contractor_requirement_items' as any).update(patch).eq('id', id); if (error) throw error; }, onSuccess: () => qc.invalidateQueries({ queryKey: ['contractor-readiness', 'settings'] }) });
  const addItem = useMutation({ mutationFn: async (input: any) => { const tenantId = await requireTenantId(); const { error } = await supabase.from('contractor_requirement_items' as any).insert({ tenant_id: tenantId, template_id: query.data?.template.id, ...input }); if (error) throw error; }, onSuccess: () => qc.invalidateQueries({ queryKey: ['contractor-readiness', 'settings'] }) });
  const savePolicy = useMutation({ mutationFn: async (patch: any) => { const tenantId = await requireTenantId(); const { data: existing } = await supabase.from('contractor_readiness_policies' as any).select('id').eq('tenant_id', tenantId).eq('scope_type', 'workspace').maybeSingle(); const operation = existing ? supabase.from('contractor_readiness_policies' as any).update(patch).eq('id', (existing as any).id) : supabase.from('contractor_readiness_policies' as any).insert({ tenant_id: tenantId, scope_type: 'workspace', default_template_id: query.data?.template.id, ...patch }); const { error } = await operation; if (error) throw error; }, onSuccess: () => qc.invalidateQueries({ queryKey: ['contractor-readiness', 'settings'] }) });
  return { ...query, updateItem, addItem, savePolicy };
}

export default function ContractorSettingsPage() {
  const settings = useReadinessSettings();
  const [policy, setPolicy] = useState<any>({});
  const [addOpen, setAddOpen] = useState(false);
  useEffect(() => { if (settings.data?.policy) setPolicy(settings.data.policy); }, [settings.data?.policy]);
  if (settings.isLoading) return <div className="p-6 text-muted-foreground">Loading policy…</div>;
  if (settings.error) return <div className="p-6 text-red-700">{settings.error instanceof Error ? settings.error.message : 'Could not load settings'}</div>;
  const savePolicy = async () => { try { await settings.savePolicy.mutateAsync({ enforce_work_gate: !!policy.enforce_work_gate, enforce_contract_gate: !!policy.enforce_contract_gate, enforce_payment_gate: !!policy.enforce_payment_gate, reminder_days: policy.reminder_days ?? [90,60,30,7,0] }); toast.success('Readiness policy saved'); } catch (e) { toast.error(e instanceof Error ? e.message : 'Save failed'); } };
  return <div className="mx-auto max-w-5xl space-y-6 p-4 sm:p-6"><Link to="/contractor-readiness" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Contractor Readiness</Link><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-emerald-700"><Settings2 className="h-4 w-4" />Module policy</div><h1 className="mt-2 text-3xl font-bold">Qualification controls</h1><p className="mt-1 text-sm text-muted-foreground">Configure the standard checklist and decide when projOS must stop mobilization, contract execution, or payment approval.</p></div>
    <Card><CardHeader><CardTitle>Deterministic gates</CardTitle><CardDescription>When enabled, a company without a matching qualification case is also blocked at this workspace scope. Project and client policies can override these settings later.</CardDescription></CardHeader><CardContent className="divide-y">{[['enforce_work_gate','Work / mobilization','Prevent an assignment from becoming active until work requirements are verified.'],['enforce_contract_gate','Contract execution','Prevent a subcontract from being executed until work and contract requirements are verified.'],['enforce_payment_gate','Payment approval','Prevent invoice approval/payment until tax and all upstream requirements are verified.']].map(([key,label,description]) => <div key={key} className="flex items-center gap-4 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><ShieldCheck className="h-5 w-5" /></div><div className="flex-1"><p className="font-semibold">{label}</p><p className="text-xs text-muted-foreground">{description}</p></div><Switch checked={!!policy[key]} onCheckedChange={(value) => setPolicy({ ...policy, [key]: value })} /></div>)}<Button className="mt-4" onClick={savePolicy}><Save className="mr-2 h-4 w-4" />Save policy</Button></CardContent></Card>
    <Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>{settings.data?.template.name}</CardTitle><CardDescription>{settings.data?.template.description}</CardDescription></div><Button size="sm" onClick={() => setAddOpen(true)}><Plus className="mr-2 h-4 w-4" />Add requirement</Button></CardHeader><CardContent className="space-y-2">{settings.data?.items.map((item: any) => <div key={item.id} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_150px_auto]"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.title}</p>{item.legally_required && <span className="inline-flex items-center gap-1 text-[10px] font-bold uppercase text-red-700"><LockKeyhole className="h-3 w-3" />No waiver</span>}</div><p className="mt-1 text-xs text-muted-foreground">{item.description}</p></div><Select value={item.gate_type} onValueChange={async (gate_type) => { try { await settings.updateItem.mutateAsync({ id: item.id, patch: { gate_type } }); toast.success('Gate updated'); } catch (e) { toast.error(e instanceof Error ? e.message : 'Update failed'); } }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="work">Work gate</SelectItem><SelectItem value="contract">Contract gate</SelectItem><SelectItem value="payment">Payment gate</SelectItem><SelectItem value="informational">Informational</SelectItem></SelectContent></Select><div className="flex items-center gap-2"><Label className="text-xs">Required</Label><Switch checked={item.required} onCheckedChange={async (required) => { try { await settings.updateItem.mutateAsync({ id: item.id, patch: { required } }); } catch (e) { toast.error(e instanceof Error ? e.message : 'Update failed'); } }} /></div></div>)}</CardContent></Card>
    <AddRequirementDialog open={addOpen} onOpenChange={setAddOpen} onAdd={settings.addItem.mutateAsync} nextOrder={(settings.data?.items.length ?? 0) * 10 + 10} />
  </div>;
}

function AddRequirementDialog({ open, onOpenChange, onAdd, nextOrder }: any) { const [title,setTitle]=useState(''); const [code,setCode]=useState(''); const [description,setDescription]=useState(''); const [category,setCategory]=useState('other'); const [gate,setGate]=useState('contract'); const [required,setRequired]=useState(true); const [legal,setLegal]=useState(false); const [expiration,setExpiration]=useState(false); const [busy,setBusy]=useState(false); const submit=async()=>{if(!title.trim())return toast.error('Title is required');setBusy(true);try{await onAdd({requirement_code:(code||title).toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''),title:title.trim(),description:description.trim()||null,category,gate_type:gate,required,legally_required:legal,verification_required:true,expiration_required:expiration,sort_order:nextOrder});toast.success('Requirement added');onOpenChange(false);setTitle('');setCode('');setDescription('');}catch(e){toast.error(e instanceof Error?e.message:'Could not add requirement')}finally{setBusy(false)}}; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add checklist requirement</DialogTitle><DialogDescription>New cases will snapshot this requirement. Existing cases remain historically stable.</DialogDescription></DialogHeader><div className="space-y-3"><div><Label>Title *</Label><Input className="mt-1" value={title} onChange={(e)=>setTitle(e.target.value)} /></div><div><Label>Description</Label><Input className="mt-1" value={description} onChange={(e)=>setDescription(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><Label>Category</Label><Select value={category} onValueChange={setCategory}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{['identity','tax','license','insurance','safety','financial','experience','agreement','other'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Gate</Label><Select value={gate} onValueChange={setGate}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent>{['work','contract','payment','informational'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div><div className="flex flex-wrap gap-5"><Toggle label="Required" value={required} set={setRequired}/><Toggle label="Legally required" value={legal} set={setLegal}/><Toggle label="Needs expiration" value={expiration} set={setExpiration}/></div></div><DialogFooter><Button onClick={submit} disabled={busy}>Add requirement</Button></DialogFooter></DialogContent></Dialog>; }
function Toggle({label,value,set}:any){return <label className="flex items-center gap-2 text-sm"><Switch checked={value} onCheckedChange={set}/>{label}</label>}
