BEGIN;

-- One evidence-backed accountability spine for owner walks, inspections,
-- property-management rounds, maintenance work, and consultant observations.

CREATE TABLE IF NOT EXISTS public.field_visits (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  property_id uuid REFERENCES public.properties(id) ON DELETE SET NULL,
  title text NOT NULL CHECK (length(trim(title)) BETWEEN 1 AND 180),
  visit_type text NOT NULL DEFAULT 'property_manager_walk'
    CHECK (visit_type IN ('owner_walk','apas_inspection','property_manager_walk','maintenance_walk','crew_update','other')),
  visited_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'triage' CHECK (status IN ('draft','triage','active','complete')),
  notes text,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.field_accountability_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  property_id uuid REFERENCES public.properties(id) ON DELETE SET NULL,
  visit_id uuid REFERENCES public.field_visits(id) ON DELETE SET NULL,
  item_number bigint GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL CHECK (length(trim(title)) BETWEEN 1 AND 180),
  description text,
  category text NOT NULL DEFAULT 'other'
    CHECK (category IN ('life_safety','water_intrusion','building_envelope','grounds','cleanliness','electrical','plumbing','hvac','structural','accessibility','security','other')),
  severity text NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
  location_label text,
  lat numeric,
  lng numeric,
  status text NOT NULL DEFAULT 'needs_triage'
    CHECK (status IN ('needs_triage','assigned','in_progress','ready_for_review','verified','reopened','deferred','rejected')),
  ball_in_court text NOT NULL DEFAULT 'property_management'
    CHECK (ball_in_court IN ('apas','property_management','maintenance','owner','vendor')),
  responsible_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  responsible_contact_id uuid,
  responsible_organization_id uuid REFERENCES public.organizations(id) ON DELETE SET NULL,
  work_order_id uuid REFERENCES public.work_orders(id) ON DELETE SET NULL,
  source_type text,
  source_record_id uuid,
  due_date date,
  repeat_count integer NOT NULL DEFAULT 0 CHECK (repeat_count >= 0),
  owner_visible boolean NOT NULL DEFAULT true,
  owner_verification_required boolean NOT NULL DEFAULT false,
  ready_for_review_at timestamptz,
  verified_at timestamptz,
  verified_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reopened_at timestamptz,
  archived_at timestamptz,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.field_accountability_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  visit_id uuid REFERENCES public.field_visits(id) ON DELETE CASCADE,
  item_id uuid REFERENCES public.field_accountability_items(id) ON DELETE CASCADE,
  photo_id uuid NOT NULL UNIQUE REFERENCES public.photos(id) ON DELETE CASCADE,
  evidence_type text NOT NULL DEFAULT 'observation'
    CHECK (evidence_type IN ('observation','before','progress','after')),
  sort_order integer NOT NULL DEFAULT 0,
  ai_suggestion jsonb NOT NULL DEFAULT '{}'::jsonb,
  ai_approved_at timestamptz,
  ai_approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (visit_id IS NOT NULL OR item_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS public.field_photo_annotations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.field_accountability_items(id) ON DELETE CASCADE,
  photo_id uuid NOT NULL REFERENCES public.photos(id) ON DELETE CASCADE,
  x numeric NOT NULL CHECK (x >= 0 AND x <= 1),
  y numeric NOT NULL CHECK (y >= 0 AND y <= 1),
  label text NOT NULL CHECK (length(trim(label)) BETWEEN 1 AND 500),
  color text NOT NULL DEFAULT '#f59e0b',
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.field_accountability_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.field_accountability_items(id) ON DELETE CASCADE,
  photo_id uuid REFERENCES public.photos(id) ON DELETE SET NULL,
  annotation_id uuid REFERENCES public.field_photo_annotations(id) ON DELETE SET NULL,
  body text NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 10000),
  visibility text NOT NULL DEFAULT 'owner' CHECK (visibility IN ('owner','internal')),
  author_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.field_accountability_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.field_accountability_items(id) ON DELETE CASCADE,
  action text NOT NULL,
  from_status text,
  to_status text,
  note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS field_visits_project_date_idx ON public.field_visits(project_id, visited_at DESC);
CREATE INDEX IF NOT EXISTS field_items_project_status_idx ON public.field_accountability_items(project_id, status, due_date);
CREATE INDEX IF NOT EXISTS field_items_project_owner_idx ON public.field_accountability_items(project_id, owner_visible, verified_at DESC);
CREATE INDEX IF NOT EXISTS field_photos_item_type_idx ON public.field_accountability_photos(item_id, evidence_type, sort_order);
CREATE INDEX IF NOT EXISTS field_comments_item_date_idx ON public.field_accountability_comments(item_id, created_at);
CREATE INDEX IF NOT EXISTS field_events_item_date_idx ON public.field_accountability_events(item_id, created_at);

CREATE OR REPLACE FUNCTION public.field_project_belongs_to_tenant(p_project_id uuid, p_tenant_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.projects project
    LEFT JOIN public.properties property ON property.id = project.property_id
    LEFT JOIN public.clients client ON client.id = project.client_id
    LEFT JOIN public.profiles creator ON creator.user_id = project.created_by
    WHERE project.id = p_project_id
      AND p_tenant_id = COALESCE(property.workspace_id, client.workspace_id, creator.workspace_id)
  );
$$;

CREATE OR REPLACE FUNCTION public.field_accountability_set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS field_visits_updated_at ON public.field_visits;
CREATE TRIGGER field_visits_updated_at BEFORE UPDATE ON public.field_visits
FOR EACH ROW EXECUTE FUNCTION public.field_accountability_set_updated_at();

DROP TRIGGER IF EXISTS field_items_updated_at ON public.field_accountability_items;
CREATE TRIGGER field_items_updated_at BEFORE UPDATE ON public.field_accountability_items
FOR EACH ROW EXECUTE FUNCTION public.field_accountability_set_updated_at();

CREATE OR REPLACE FUNCTION public.validate_field_accountability_linkage()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE
  v_project uuid;
  v_tenant uuid;
BEGIN
  SELECT p.tenant_id, p.project_id INTO v_tenant, v_project
  FROM public.field_accountability_items p WHERE p.id = NEW.item_id;
  IF NEW.item_id IS NOT NULL AND (v_tenant IS DISTINCT FROM NEW.tenant_id OR v_project IS DISTINCT FROM NEW.project_id) THEN
    RAISE EXCEPTION 'Accountability item must belong to the same tenant and project';
  END IF;
  IF NEW.photo_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.photos ph WHERE ph.id = NEW.photo_id AND ph.tenant_id = NEW.tenant_id AND ph.project_id = NEW.project_id
  ) THEN
    RAISE EXCEPTION 'Photo must belong to the same tenant and project';
  END IF;
  IF TG_TABLE_NAME <> 'field_accountability_photos'
    AND NEW.item_id IS NOT NULL AND NEW.photo_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM public.field_accountability_photos fp
      WHERE fp.item_id = NEW.item_id AND fp.photo_id = NEW.photo_id
    ) THEN
    RAISE EXCEPTION 'Photo must be attached to this accountability item';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_field_accountability_item()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.status NOT IN ('needs_triage','assigned') THEN
    RAISE EXCEPTION 'New accountability items must begin in triage or assigned status';
  END IF;
  IF NOT public.field_project_belongs_to_tenant(NEW.project_id, NEW.tenant_id) THEN
    RAISE EXCEPTION 'Project must belong to the same tenant';
  END IF;
  IF NEW.visit_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.field_visits v
    WHERE v.id = NEW.visit_id AND v.tenant_id = NEW.tenant_id AND v.project_id = NEW.project_id
  ) THEN
    RAISE EXCEPTION 'Site walk must belong to the same tenant and project';
  END IF;
  IF NEW.property_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.properties p WHERE p.id = NEW.property_id AND p.workspace_id = NEW.tenant_id
  ) THEN
    RAISE EXCEPTION 'Property must belong to the same tenant';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_field_visit()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NOT public.field_project_belongs_to_tenant(NEW.project_id, NEW.tenant_id) THEN
    RAISE EXCEPTION 'Project must belong to the same tenant';
  END IF;
  IF NEW.property_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.properties p WHERE p.id = NEW.property_id AND p.workspace_id = NEW.tenant_id
  ) THEN
    RAISE EXCEPTION 'Property must belong to the same tenant';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS field_visit_validate_linkage ON public.field_visits;
CREATE TRIGGER field_visit_validate_linkage BEFORE INSERT OR UPDATE ON public.field_visits
FOR EACH ROW EXECUTE FUNCTION public.validate_field_visit();

DROP TRIGGER IF EXISTS field_item_validate_linkage ON public.field_accountability_items;
CREATE TRIGGER field_item_validate_linkage BEFORE INSERT OR UPDATE ON public.field_accountability_items
FOR EACH ROW EXECUTE FUNCTION public.validate_field_accountability_item();

DROP TRIGGER IF EXISTS field_photos_validate_linkage ON public.field_accountability_photos;
CREATE TRIGGER field_photos_validate_linkage BEFORE INSERT OR UPDATE ON public.field_accountability_photos
FOR EACH ROW EXECUTE FUNCTION public.validate_field_accountability_linkage();
DROP TRIGGER IF EXISTS field_annotations_validate_linkage ON public.field_photo_annotations;
CREATE TRIGGER field_annotations_validate_linkage BEFORE INSERT OR UPDATE ON public.field_photo_annotations
FOR EACH ROW EXECUTE FUNCTION public.validate_field_accountability_linkage();
DROP TRIGGER IF EXISTS field_comments_validate_linkage ON public.field_accountability_comments;
CREATE TRIGGER field_comments_validate_linkage BEFORE INSERT OR UPDATE ON public.field_accountability_comments
FOR EACH ROW EXECUTE FUNCTION public.validate_field_accountability_linkage();

CREATE OR REPLACE FUNCTION public.enforce_field_after_photo_limit()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.evidence_type = 'after' AND NEW.item_id IS NOT NULL AND (
    SELECT count(*) FROM public.field_accountability_photos fp
    WHERE fp.item_id = NEW.item_id AND fp.evidence_type = 'after' AND fp.id IS DISTINCT FROM NEW.id
  ) >= 3 THEN
    RAISE EXCEPTION 'A condition may have no more than three after photos';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS field_after_photo_limit ON public.field_accountability_photos;
CREATE TRIGGER field_after_photo_limit BEFORE INSERT OR UPDATE ON public.field_accountability_photos
FOR EACH ROW EXECUTE FUNCTION public.enforce_field_after_photo_limit();

CREATE OR REPLACE FUNCTION public.log_field_accountability_status()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.field_accountability_events(tenant_id, project_id, item_id, action, to_status, actor_id)
    VALUES (NEW.tenant_id, NEW.project_id, NEW.id, 'created', NEW.status, NEW.created_by);
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.field_accountability_events(tenant_id, project_id, item_id, action, from_status, to_status, actor_id)
    VALUES (NEW.tenant_id, NEW.project_id, NEW.id, 'status_changed', OLD.status, NEW.status, auth.uid());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS field_item_status_audit ON public.field_accountability_items;
CREATE TRIGGER field_item_status_audit AFTER INSERT OR UPDATE OF status ON public.field_accountability_items
FOR EACH ROW EXECUTE FUNCTION public.log_field_accountability_status();

CREATE OR REPLACE FUNCTION public.transition_field_accountability_item(
  p_item_id uuid,
  p_target_status text,
  p_note text DEFAULT NULL
) RETURNS public.field_accountability_items
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_item public.field_accountability_items;
  v_kind text := public.current_portal_kind();
  v_after_count integer;
BEGIN
  SELECT * INTO v_item FROM public.field_accountability_items WHERE id = p_item_id FOR UPDATE;
  IF v_item.id IS NULL THEN RAISE EXCEPTION 'Accountability item not found'; END IF;

  IF v_kind = 'owner' THEN
    IF NOT public.owner_can_access_project(v_item.project_id) OR NOT v_item.owner_visible THEN
      RAISE EXCEPTION 'Not authorized for this project';
    END IF;
    IF p_target_status NOT IN ('verified','reopened') THEN
      RAISE EXCEPTION 'Owners may only accept or reopen work';
    END IF;
    IF p_target_status = 'reopened' AND length(trim(COALESCE(p_note,''))) < 3 THEN
      RAISE EXCEPTION 'A reason is required to reopen work';
    END IF;
    IF p_target_status = 'verified' AND v_item.status <> 'ready_for_review' THEN
      RAISE EXCEPTION 'Only work ready for review can be accepted';
    END IF;
    IF p_target_status = 'reopened' AND v_item.status NOT IN ('ready_for_review','verified') THEN
      RAISE EXCEPTION 'Only submitted or verified work can be reopened';
    END IF;
  ELSIF v_kind <> 'main' AND NOT public.is_super_admin() THEN
    RAISE EXCEPTION 'Only project staff or an authorized owner may change status';
  ELSIF v_item.tenant_id <> public.current_tenant_id() AND NOT public.is_super_admin() THEN
    RAISE EXCEPTION 'Not authorized for this tenant';
  END IF;

  IF p_target_status NOT IN ('needs_triage','assigned','in_progress','ready_for_review','verified','reopened','deferred','rejected') THEN
    RAISE EXCEPTION 'Invalid target status';
  END IF;

  IF v_kind <> 'owner' AND NOT public.is_super_admin() AND NOT (
    (v_item.status = 'needs_triage' AND p_target_status IN ('assigned','deferred','rejected')) OR
    (v_item.status = 'assigned' AND p_target_status IN ('in_progress','deferred','rejected')) OR
    (v_item.status IN ('in_progress','reopened') AND p_target_status IN ('assigned','ready_for_review','deferred')) OR
    (v_item.status = 'ready_for_review' AND p_target_status IN ('verified','reopened')) OR
    (v_item.status = 'verified' AND p_target_status = 'reopened') OR
    (v_item.status IN ('deferred','rejected') AND p_target_status = 'assigned') OR
    v_item.status = p_target_status
  ) THEN
    RAISE EXCEPTION 'Invalid accountability status transition from % to %', v_item.status, p_target_status;
  END IF;

  IF p_target_status = 'ready_for_review' THEN
    SELECT count(*) INTO v_after_count FROM public.field_accountability_photos
    WHERE item_id = p_item_id AND evidence_type = 'after';
    IF v_after_count < 1 THEN RAISE EXCEPTION 'At least one after photo is required before review'; END IF;
  END IF;

  UPDATE public.field_accountability_items
  SET status = p_target_status,
      ready_for_review_at = CASE WHEN p_target_status = 'ready_for_review' THEN now() ELSE ready_for_review_at END,
      verified_at = CASE WHEN p_target_status = 'verified' THEN now() ELSE NULL END,
      verified_by = CASE WHEN p_target_status = 'verified' THEN auth.uid() ELSE NULL END,
      reopened_at = CASE WHEN p_target_status = 'reopened' THEN now() ELSE reopened_at END,
      ball_in_court = CASE
        WHEN p_target_status = 'ready_for_review' THEN 'apas'
        WHEN p_target_status = 'reopened' AND v_kind = 'owner' THEN 'property_management'
        ELSE ball_in_court END
  WHERE id = p_item_id RETURNING * INTO v_item;

  IF p_note IS NOT NULL AND trim(p_note) <> '' THEN
    INSERT INTO public.field_accountability_events(tenant_id, project_id, item_id, action, to_status, note, actor_id)
    VALUES (v_item.tenant_id, v_item.project_id, v_item.id, 'status_note', p_target_status, trim(p_note), auth.uid());
  END IF;
  RETURN v_item;
END;
$$;

REVOKE ALL ON FUNCTION public.transition_field_accountability_item(uuid,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.transition_field_accountability_item(uuid,text,text) TO authenticated;

ALTER TABLE public.field_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_accountability_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_accountability_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_photo_annotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_accountability_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_accountability_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY field_visits_staff ON public.field_visits FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY field_visits_owner_read ON public.field_visits FOR SELECT TO authenticated
  USING (public.owner_can_access_project(project_id));

CREATE POLICY field_items_staff ON public.field_accountability_items FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY field_items_owner_read ON public.field_accountability_items FOR SELECT TO authenticated
  USING (owner_visible AND archived_at IS NULL AND public.owner_can_access_project(project_id));

CREATE POLICY field_photos_staff ON public.field_accountability_photos FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY field_photos_owner_read ON public.field_accountability_photos FOR SELECT TO authenticated
  USING (item_id IS NOT NULL AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.field_accountability_items i WHERE i.id = item_id AND i.owner_visible));

CREATE POLICY field_annotations_staff ON public.field_photo_annotations FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY field_annotations_owner_read ON public.field_photo_annotations FOR SELECT TO authenticated
  USING (public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.field_accountability_items i WHERE i.id = item_id AND i.owner_visible));
CREATE POLICY field_annotations_owner_create ON public.field_photo_annotations FOR INSERT TO authenticated
  WITH CHECK (tenant_id = public.current_portal_tenant_id() AND created_by = auth.uid()
    AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.field_accountability_items i WHERE i.id = item_id AND i.owner_visible));

CREATE POLICY field_comments_staff ON public.field_accountability_comments FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY field_comments_owner_read ON public.field_accountability_comments FOR SELECT TO authenticated
  USING (visibility = 'owner' AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.field_accountability_items i WHERE i.id = item_id AND i.owner_visible));
CREATE POLICY field_comments_owner_create ON public.field_accountability_comments FOR INSERT TO authenticated
  WITH CHECK (tenant_id = public.current_portal_tenant_id() AND visibility = 'owner' AND author_id = auth.uid()
    AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.field_accountability_items i WHERE i.id = item_id AND i.owner_visible));

CREATE POLICY field_events_staff_read ON public.field_accountability_events FOR SELECT TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY field_events_owner_read ON public.field_accountability_events FOR SELECT TO authenticated
  USING (public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.field_accountability_items i WHERE i.id = item_id AND i.owner_visible));

-- An owner can read only project-photo objects that are evidence on a visible
-- accountability item. Main users retain the existing tenant policy.
DROP POLICY IF EXISTS project_photos_owner_accountability_read ON storage.objects;
CREATE POLICY project_photos_owner_accountability_read ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'project-photos'
  AND public.current_portal_kind() = 'owner'
  AND EXISTS (
    SELECT 1
    FROM public.photos ph
    JOIN public.field_accountability_photos fp ON fp.photo_id = ph.id
    JOIN public.field_accountability_items i ON i.id = fp.item_id
    WHERE ph.storage_path = storage.objects.name
      AND i.owner_visible
      AND public.owner_can_access_project(i.project_id)
  )
);

-- Owner portal must be able to read the photos rows used by visible items.
DROP POLICY IF EXISTS photos_owner_accountability_read ON public.photos;
CREATE POLICY photos_owner_accountability_read ON public.photos FOR SELECT TO authenticated
USING (
  public.current_portal_kind() = 'owner'
  AND EXISTS (
    SELECT 1
    FROM public.field_accountability_photos fp
    JOIN public.field_accountability_items i ON i.id = fp.item_id
    WHERE fp.photo_id = photos.id
      AND i.owner_visible
      AND public.owner_can_access_project(i.project_id)
  )
);

GRANT SELECT, INSERT, UPDATE ON public.field_visits TO authenticated;
GRANT SELECT, INSERT ON public.field_accountability_items TO authenticated;
REVOKE UPDATE ON public.field_accountability_items FROM authenticated;
GRANT UPDATE (
  title, description, category, severity, location_label, lat, lng,
  ball_in_court, responsible_user_id, responsible_contact_id,
  responsible_organization_id, work_order_id, source_type, source_record_id,
  due_date, repeat_count, owner_visible, owner_verification_required,
  archived_at, updated_at
) ON public.field_accountability_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.field_accountability_photos TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.field_photo_annotations TO authenticated;
GRANT SELECT, INSERT ON public.field_accountability_comments TO authenticated;
GRANT SELECT ON public.field_accountability_events TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
