BEGIN;

-- Durable Project Conditions Register.
-- This is the client/reporting-grade register layer that can be sourced from
-- Field Accountability while preserving APAS/internal review from owner-visible
-- summaries.

CREATE TABLE IF NOT EXISTS public.project_condition_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  field_item_id uuid REFERENCES public.field_accountability_items(id) ON DELETE SET NULL,
  condition_number bigint GENERATED BY DEFAULT AS IDENTITY,
  source_system text NOT NULL DEFAULT 'projos',
  source_record_id text,
  building_or_area text NOT NULL DEFAULT 'Project area' CHECK (length(trim(building_or_area)) BETWEEN 1 AND 180),
  elevation text,
  floor text,
  unit text,
  element text NOT NULL CHECK (length(trim(element)) BETWEEN 1 AND 240),
  location_label text,
  classification text NOT NULL DEFAULT 'needs_engineer_determination'
    CHECK (classification IN ('structural','non_structural','mixed','needs_engineer_determination')),
  classification_status text NOT NULL DEFAULT 'needs_review'
    CHECK (classification_status IN ('draft','needs_review','engineer_approved','returned')),
  observed_condition text NOT NULL CHECK (length(trim(observed_condition)) BETWEEN 1 AND 12000),
  condition_category text NOT NULL DEFAULT 'other' CHECK (length(trim(condition_category)) BETWEEN 1 AND 120),
  severity text NOT NULL DEFAULT 'to_be_determined'
    CHECK (severity IN ('low','moderate','high','critical','to_be_determined')),
  quantity numeric,
  quantity_unit text,
  repair_type text,
  spec_reference text,
  permit_status text NOT NULL DEFAULT 'not_determined'
    CHECK (permit_status IN ('not_determined','no_permit_expected','permit_required','held_pending_permit','permit_issued')),
  owner_signoff_status text NOT NULL DEFAULT 'not_ready'
    CHECK (owner_signoff_status IN ('not_ready','ready_for_owner','pending','approved','returned')),
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','needs_apas_review','needs_engineer_review','ready_for_owner','held_pending_permit','released_for_contractor_pricing','in_construction','verified_complete','closed','void')),
  ai_suggestion text,
  ai_confidence numeric CHECK (ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)),
  human_review_required boolean NOT NULL DEFAULT true,
  client_publish_status text NOT NULL DEFAULT 'internal_only'
    CHECK (client_publish_status IN ('internal_only','ready_to_publish','published_to_client','returned_before_publish')),
  client_summary text,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(project_id, source_system, source_record_id)
);

CREATE TABLE IF NOT EXISTS public.project_condition_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  condition_id uuid NOT NULL REFERENCES public.project_condition_records(id) ON DELETE CASCADE,
  body text NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 10000),
  role text,
  audience text NOT NULL DEFAULT 'internal' CHECK (audience IN ('internal','client_visible')),
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_condition_notations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  condition_id uuid NOT NULL REFERENCES public.project_condition_records(id) ON DELETE CASCADE,
  notation_type text NOT NULL DEFAULT 'observed_condition' CHECK (length(trim(notation_type)) BETWEEN 1 AND 120),
  body text NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 10000),
  audience text NOT NULL DEFAULT 'internal' CHECK (audience IN ('internal','client_visible')),
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_condition_photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  condition_id uuid NOT NULL REFERENCES public.project_condition_records(id) ON DELETE CASCADE,
  field_photo_id uuid REFERENCES public.field_accountability_photos(id) ON DELETE SET NULL,
  photo_id uuid REFERENCES public.photos(id) ON DELETE SET NULL,
  evidence_type text NOT NULL DEFAULT 'observation'
    CHECK (evidence_type IN ('observation','before','progress','after','reference')),
  audience text NOT NULL DEFAULT 'internal' CHECK (audience IN ('internal','client_visible')),
  sort_order integer NOT NULL DEFAULT 0,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_condition_audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  condition_id uuid NOT NULL REFERENCES public.project_condition_records(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (length(trim(event_type)) BETWEEN 1 AND 120),
  note text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_id uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS project_conditions_project_status_idx
  ON public.project_condition_records(project_id, status, client_publish_status, updated_at DESC);
CREATE INDEX IF NOT EXISTS project_conditions_project_class_idx
  ON public.project_condition_records(project_id, classification, classification_status);
CREATE INDEX IF NOT EXISTS project_conditions_field_item_idx
  ON public.project_condition_records(field_item_id) WHERE field_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS project_condition_comments_condition_idx
  ON public.project_condition_comments(condition_id, created_at);
CREATE INDEX IF NOT EXISTS project_condition_notations_condition_idx
  ON public.project_condition_notations(condition_id, created_at);
CREATE INDEX IF NOT EXISTS project_condition_photos_condition_idx
  ON public.project_condition_photos(condition_id, sort_order);
CREATE INDEX IF NOT EXISTS project_condition_audit_condition_idx
  ON public.project_condition_audit_events(condition_id, created_at);

CREATE OR REPLACE FUNCTION public.project_condition_set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS project_condition_records_updated_at ON public.project_condition_records;
CREATE TRIGGER project_condition_records_updated_at BEFORE UPDATE ON public.project_condition_records
FOR EACH ROW EXECUTE FUNCTION public.project_condition_set_updated_at();

CREATE OR REPLACE FUNCTION public.validate_project_condition_record()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NOT public.field_project_belongs_to_tenant(NEW.project_id, NEW.tenant_id) THEN
    RAISE EXCEPTION 'Project must belong to the same tenant';
  END IF;
  IF NEW.field_item_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.field_accountability_items item
    WHERE item.id = NEW.field_item_id
      AND item.tenant_id = NEW.tenant_id
      AND item.project_id = NEW.project_id
  ) THEN
    RAISE EXCEPTION 'Linked field accountability item must belong to the same tenant and project';
  END IF;
  IF NEW.client_publish_status IN ('ready_to_publish','published_to_client')
     AND length(trim(COALESCE(NEW.client_summary, ''))) < 1 THEN
    RAISE EXCEPTION 'Client-visible project conditions require a client summary';
  END IF;
  IF NEW.classification = 'needs_engineer_determination' AND NEW.classification_status = 'engineer_approved' THEN
    RAISE EXCEPTION 'Engineer approval requires a determined classification';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_project_condition_child()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.project_condition_records record
    WHERE record.id = NEW.condition_id
      AND record.tenant_id = NEW.tenant_id
      AND record.project_id = NEW.project_id
  ) THEN
    RAISE EXCEPTION 'Project condition child row must belong to the same condition, tenant, and project';
  END IF;
  IF TG_TABLE_NAME = 'project_condition_photos' AND NEW.field_photo_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.field_accountability_photos photo
    WHERE photo.id = NEW.field_photo_id
      AND photo.tenant_id = NEW.tenant_id
      AND photo.project_id = NEW.project_id
  ) THEN
    RAISE EXCEPTION 'Linked field photo must belong to the same tenant and project';
  END IF;
  IF TG_TABLE_NAME = 'project_condition_photos' AND NEW.photo_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.photos photo
    WHERE photo.id = NEW.photo_id
      AND photo.tenant_id = NEW.tenant_id
      AND photo.project_id = NEW.project_id
  ) THEN
    RAISE EXCEPTION 'Linked photo must belong to the same tenant and project';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS project_condition_record_validate ON public.project_condition_records;
CREATE TRIGGER project_condition_record_validate BEFORE INSERT OR UPDATE ON public.project_condition_records
FOR EACH ROW EXECUTE FUNCTION public.validate_project_condition_record();

DROP TRIGGER IF EXISTS project_condition_comments_validate ON public.project_condition_comments;
CREATE TRIGGER project_condition_comments_validate BEFORE INSERT OR UPDATE ON public.project_condition_comments
FOR EACH ROW EXECUTE FUNCTION public.validate_project_condition_child();

DROP TRIGGER IF EXISTS project_condition_notations_validate ON public.project_condition_notations;
CREATE TRIGGER project_condition_notations_validate BEFORE INSERT OR UPDATE ON public.project_condition_notations
FOR EACH ROW EXECUTE FUNCTION public.validate_project_condition_child();

DROP TRIGGER IF EXISTS project_condition_photos_validate ON public.project_condition_photos;
CREATE TRIGGER project_condition_photos_validate BEFORE INSERT OR UPDATE ON public.project_condition_photos
FOR EACH ROW EXECUTE FUNCTION public.validate_project_condition_child();

DROP TRIGGER IF EXISTS project_condition_audit_validate ON public.project_condition_audit_events;
CREATE TRIGGER project_condition_audit_validate BEFORE INSERT OR UPDATE ON public.project_condition_audit_events
FOR EACH ROW EXECUTE FUNCTION public.validate_project_condition_child();

CREATE OR REPLACE FUNCTION public.log_project_condition_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.project_condition_audit_events(tenant_id, project_id, condition_id, event_type, actor_id, note)
    VALUES (NEW.tenant_id, NEW.project_id, NEW.id, 'condition.created', NEW.created_by, 'Project condition created');
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.project_condition_audit_events(tenant_id, project_id, condition_id, event_type, actor_id, note, metadata)
    VALUES (
      NEW.tenant_id,
      NEW.project_id,
      NEW.id,
      'condition.status_changed',
      auth.uid(),
      'Project condition status changed',
      jsonb_build_object('from_status', OLD.status, 'to_status', NEW.status)
    );
  ELSIF NEW.client_publish_status IS DISTINCT FROM OLD.client_publish_status THEN
    INSERT INTO public.project_condition_audit_events(tenant_id, project_id, condition_id, event_type, actor_id, note, metadata)
    VALUES (
      NEW.tenant_id,
      NEW.project_id,
      NEW.id,
      'condition.publish_status_changed',
      auth.uid(),
      'Project condition publish status changed',
      jsonb_build_object('from_status', OLD.client_publish_status, 'to_status', NEW.client_publish_status)
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS project_condition_change_audit ON public.project_condition_records;
CREATE TRIGGER project_condition_change_audit AFTER INSERT OR UPDATE OF status, client_publish_status ON public.project_condition_records
FOR EACH ROW EXECUTE FUNCTION public.log_project_condition_change();

ALTER TABLE public.project_condition_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_condition_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_condition_notations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_condition_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_condition_audit_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY project_conditions_staff ON public.project_condition_records FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY project_conditions_owner_read ON public.project_condition_records FOR SELECT TO authenticated
  USING (client_publish_status IN ('ready_to_publish','published_to_client') AND public.owner_can_access_project(project_id));

CREATE POLICY project_condition_comments_staff ON public.project_condition_comments FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY project_condition_comments_owner_read ON public.project_condition_comments FOR SELECT TO authenticated
  USING (audience = 'client_visible' AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.project_condition_records record WHERE record.id = condition_id AND record.client_publish_status IN ('ready_to_publish','published_to_client')));

CREATE POLICY project_condition_notations_staff ON public.project_condition_notations FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY project_condition_notations_owner_read ON public.project_condition_notations FOR SELECT TO authenticated
  USING (audience = 'client_visible' AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.project_condition_records record WHERE record.id = condition_id AND record.client_publish_status IN ('ready_to_publish','published_to_client')));

CREATE POLICY project_condition_photos_staff ON public.project_condition_photos FOR ALL TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin())
  WITH CHECK ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());
CREATE POLICY project_condition_photos_owner_read ON public.project_condition_photos FOR SELECT TO authenticated
  USING (audience = 'client_visible' AND public.owner_can_access_project(project_id)
    AND EXISTS (SELECT 1 FROM public.project_condition_records record WHERE record.id = condition_id AND record.client_publish_status IN ('ready_to_publish','published_to_client')));

CREATE POLICY project_condition_audit_staff_read ON public.project_condition_audit_events FOR SELECT TO authenticated
  USING ((public.current_portal_kind() = 'main' AND tenant_id = public.current_tenant_id() AND public.field_project_belongs_to_tenant(project_id, tenant_id)) OR public.is_super_admin());

GRANT SELECT, INSERT ON public.project_condition_records TO authenticated;
REVOKE UPDATE ON public.project_condition_records FROM authenticated;
GRANT UPDATE (
  building_or_area, elevation, floor, unit, element, location_label,
  classification, classification_status, observed_condition, condition_category,
  severity, quantity, quantity_unit, repair_type, spec_reference, permit_status,
  owner_signoff_status, status, ai_suggestion, ai_confidence,
  human_review_required, client_publish_status, client_summary, updated_at
) ON public.project_condition_records TO authenticated;
GRANT SELECT, INSERT ON public.project_condition_comments TO authenticated;
GRANT SELECT, INSERT ON public.project_condition_notations TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.project_condition_photos TO authenticated;
GRANT SELECT ON public.project_condition_audit_events TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
